eth-brownie/brownie

- .gitignore
- README.md
- __main__.py
- brownie-install.sh
- config.json
- docs/console.rst
- docs/init.rst
- docs/install.rst
- lib/components/alert.py
- lib/components/config.py
- lib/components/eth.py
- lib/components/network.py
- lib/console.py
- lib/deploy.py
- lib/init.py
- lib/test.py
- requirements.txt
-docopts are implemented
-less hacky approach to CONFIG
-changed requirement to python3.6
-use venv instead of virtualenv
closes #17
> Restructure

- lib/components/compile.py
- lib/components/contract.py
- lib/components/eth.py
- lib/components/network.py
better compile logic, moved to compile.py  fixes #21
> better compile logic, moved to compile.py  fixes #21

- CHANGELOG
- __main__.py
- docs/conf.py
- lib/components/bytecode.py
- lib/coverage.py
- lib/test.py
- Add --always-transact flag for test and coverage
- Do not show individual methods when contract coverage is 0%
- Minor bugfixes
> Version 0.9.1

- Dockerfile
I could not build this Docker image. So I added `sudo` to Dockerfile.
> Add sudo to Dockerfile

- CHANGELOG
- __main__.py
- docs/api.rst
- docs/conf.py
- docs/tests.rst
- lib/components/account.py
- lib/components/check.py
- lib/components/contract.py
- lib/components/network.py
- lib/components/transaction.py
- lib/console.py
- lib/coverage.py
- lib/services/compiler.py
- lib/test.py
- check.true and check.false require booleans to pass
- Allow subfolders within tests/
- Only run specific tests within a file
- More efficient transaction stack trace analysis
- Improvements to compiler efficiency and functionality
- account.transfer accepts data
- add ContractTx.encode_abi
- add ContractContainer.get_method
- Bugfixes
> Brownie 0.9.5

- brownie/cli/console.py
- brownie/cli/utils/color.py
- brownie/network/contract.py
- brownie/network/event.py
- brownie/types/types.py
* add `EventDict` and `EventItem` classes to simplify accessing information about events
* modify `cli.console` and `cli.utils.colors` so new classes print properly
Documentation for this will be included in the pending update to the API docs
> Events dict

- brownie/cli/test.py
- brownie/data/config.json
- brownie/network/contract.py
- docs/config.rst
- docs/coverage.rst
- docs/tests.rst
> Changes to always_transact

- brownie/project/compiler.py
- requirements.txt
* breaking changes to `solcx` in v0.4.0
* updated `compiler.py` and `requirements.txt`
closes #108
> Solcx 0.4.0

- brownie/network/transaction.py
- brownie/project/compiler.py
- brownie/project/sources.py
* expanded `project/source.py`, all contracts are now regex'd to find function offsets
* modified `network/transaction.py` and `project/compiler.py` to use new functionality
This is a step towards #102
> Source - now with more regex

- brownie/cli/test.py
- brownie/project/sources.py
- brownie/test/coverage.py
- brownie/types/types.py
- docs/tests.rst
- refactor of `cli/test.py`, use new `TestPrinter` object for test verbosity (more progress on #102)
- apply test `setup` kwargs across all tests, allow skipping of entire modules
> Improvements to cli/test.py

- brownie/cli/test.py
- brownie/cli/utils/color.py
- brownie/project/compiler.py
- brownie/test/coverage.py
Major refactor of `cli/test.py`. Added the following improvements to the test output:
- Coverage % for entire contract
- Completion time for test module
- Count/total number of test modules to run
- Completion time for running all tests
> Improved test verbosity

- brownie/cli/test.py
- brownie/data/config.json
- brownie/exceptions.py
- brownie/network/contract.py
- brownie/network/history.py
- brownie/network/rpc.py
- brownie/project/build.py
- brownie/project/sources.py
- brownie/test/coverage.py
- docs/config.rst
- docs/tests.rst
* bugfixes, optimizations, better exception verbosity
> Final commits for v1.0.0b5

- .gitignore
- .travis.yml
- README.md
- brownie/_config.py
- brownie/cli/utils/color.py
- brownie/exceptions.py
- brownie/project/__init__.py
- brownie/project/compiler.py
- brownie/project/sources.py
- docs/api-network.rst
- docs/api.rst
- docs/debug.rst
- docs/toctree.rst
- requirements-dev.txt
- tests/brownie-test-project/brownie-config.json
- tests/brownie-test-project/contracts/Interface.sol
- tests/brownie-test-project/contracts/SafeMath.sol
- tests/brownie-test-project/contracts/Token.sol
- tests/cli/cli_init_test.py
- tests/conftest.py
- tests/project/project_init_test.py
- tox.ini
* TravisCI implemented, build passing
* Tox for running tests
* (very limited) first tests
* bugfixes
With Travis and Tox in place, the next step is to write a lot of tests.  Merging this now so that Travis is active on master.
> Add TravisCI and start of test suite

- brownie/network/account.py
- brownie/network/transaction.py
- brownie/project/build.py
- brownie/project/sources.py
- docs/api-network.rst
- docs/api-project.rst
- docs/conf.py
- docs/debug.rst
- docs/requirements.txt
- docs/tests.rst
- tox.ini
* better handling of revert strings and error messages - significant improvement in how quickly brownie executes tests
* add functionality for dev revert strings as comments, closes #40
> Revert trace

- .travis.yml
- README.md
- tox.ini
> add coveralls

- brownie/network/contract.py
- brownie/network/rpc.py
- brownie/network/transaction.py
- brownie/project/build.py
- brownie/project/compiler.py
- brownie/project/sources.py
- docs/api-network.rst
- docs/api-project.rst
- docs/compile.rst
- tests/brownie-test-project/contracts/BrownieTester.sol
- tests/brownie-test-project/contracts/ExternalCallTester.sol
- tests/brownie-test-project/contracts/Unimplemented.sol
- tests/conftest.py
- tests/network/contract/contractcall_test.py
- tests/network/transaction/attributes_test.py
- tests/network/transaction/test_attributes.py
- tests/network/transaction/test_trace.py
- tests/network/transaction/test_verbosity.py
- tests/project/build_test.py
* added ``TransactionReceipt.traceback``
* improved  ``TransactionReceipt.call_trace``
* significant refactor, cleanup, code commenting
* removed unused functions from ``project.sources`` now that ``solcast`` is fully implemented
> Tx refactor

- .travis.yml
- CHANGELOG
- brownie/cli/utils/color.py
- brownie/exceptions.py
- brownie/network/alert.py
- brownie/network/main.py
- brownie/network/rpc.py
- brownie/network/web3.py
- brownie/project/sources.py
- docs/api-network.rst
- requirements-dev.txt
- requirements.txt
- tests/cli/test_color.py
- tests/conftest.py
- tests/network/rpc/conftest.py
- tests/network/rpc/test_attach.py
- tests/network/rpc/test_launch.py
- tests/network/test_alert.py
- tests/test/plugin/conftest.py
- tox.ini
- add Windows to CI
- various bugfixes relating to Windows, tests are passing :)
- added `colorama` - support for ansi colors in Windows
- Expanded Alert functionality
> Travis windows

- .travis.yml
- CHANGELOG
- brownie/data/config.json
- brownie/exceptions.py
- brownie/network/transaction.py
- brownie/project/compiler.py
- brownie/project/main.py
- brownie/project/sources.py
- docs/api-brownie.rst
- docs/api-project.rst
- docs/compile.rst
- docs/config.rst
- docs/test-rpc.rst
- tests/conftest.py
- tests/project/conftest.py
- tests/project/test_compiler.py
- tests/project/test_sources.py
- Determine solc version using pragma
- allow multiple versions in one project
- update docs and tests
Closes #64
> Solc pragma

- brownie/cli/console.py
- brownie/cli/run.py
- brownie/network/account.py
- brownie/network/transaction.py
- brownie/project/main.py
- brownie/project/scripts.py
- brownie/test/coverage.py
- brownie/test/manager.py
- brownie/test/plugin.py
- docs/api-project.rst
- docs/api-test.rst
- docs/conf.py
- setup.py
- tests/brownie-test-project/contracts/BrownieTester.sol
- tests/cli/test_cli_main.py
- tests/conftest.py
- tests/network/account/test_account_transfer.py
- tests/network/account/test_accounts.py
- tests/network/transaction/test_attributes.py
- tests/network/transaction/test_trace.py
- tests/project/test_brownie_mix.py
- tests/project/test_compiler.py
- tests/project/test_main_project.py
* changes to how script namespaces are handled
* changes to variable and method names
* update tests, more tests
* update docs
* bump version!
> Odds and ends

- brownie/project/compiler.py
- tests/brownie-test-project/contracts/EVMTester.sol
- tests/conftest.py
- tests/network/transaction/test_attributes.py
- tests/test/plugin/test_session_fixtures.py
- tests/test/test_coverage_map.py
Added parametrized tests for revert strings and coverage evaluation
> parametrized tests

- brownie/project/compiler.py
- requirements.txt
- tests/project/test_compiler.py
updates based on changes to `semantic_version`
> use semantic_version.NpmSpec, update requirements - fixes #176

- brownie/project/compiler.py
> enable solcx logger

- docs/api-network.rst
> Expand revert registry docs

- brownie/project/compiler.py
Mostly a copypasta of code I wrote for Vyper - https://github.com/ethereum/vyper/blob/faacf1503e02b7af935a6dcf8eda4ec697ed2101/vyper/compiler.py#L177-L196
Closes #196
> Refactor _expand_row

- brownie/project/compiler.py
- requirements.txt
Updates based on breaking changes to `py-solc-ast`.
> updates for py-solc-ast 1.0.0

- brownie/__init__.py
- brownie/_config.py
- brownie/data/config.json
- brownie/exceptions.py
- brownie/network/__init__.py
- brownie/network/account.py
- brownie/network/contract.py
- brownie/network/main.py
- brownie/network/rpc.py
- brownie/network/transaction.py
- brownie/network/web3.py
- docs/api-brownie.rst
- docs/api-network.rst
- docs/config.rst
- tests/conftest.py
- tests/network/account/test_accounts.py
- tests/network/account/test_ens.py
- tests/network/account/test_pub_account.py
- tests/network/test_main_network.py
- tests/network/test_web3.py
- tox.ini
* Allow environment vars for config `'host'` setting - closes #215 
* Add ENS support - closes #216
* modify `Web3` (no longer a singleton)
* refactor of `brownie.network.accounts`
and of course, update tests and docs
> Project ID environment variables / ENS Support

- .pre-commit-config.yaml
Adds local mypy checks and runs isort in pre-commit. Resolves #219.
> Add mypy and isort to pre-commit

- brownie/_config.py
- brownie/network/transaction.py
- brownie/project/build.py
- brownie/project/compiler.py
- brownie/project/main.py
- brownie/project/scripts.py
- brownie/project/sources.py
- docs/api-project.rst
* refactoring, removed filesystem interactions in `Build` and `Sources` objects
* allow multiple contracts within `TempProject` (needed for ethPM integration)
> Project main

- .coveragerc
- brownie/project/sources.py
- requirements.txt
- setup.cfg
* bugfix in regex patterns causing some contracts to fail to load
* bumped dependencies to use new version of `py-solc-ast`
* moved coverage settings into `setup.cfg`
> Regex bugfix

- .travis.yml
use python3.7 for travis windows build
> use python3.7 for travis windows build

- CHANGELOG.md
- brownie/convert.py
* unhandled exception being raised by `eth_utils.is_hex()` when comparing certain types
* in `convert.py`, use `isinstance` instead of `type` where sane to do so
* refactor to avoid the exception
> replace type with isinstance

- brownie/project/compiler.py
- requirements.txt
* Update `solcast` dependency to latest version
> update solcast version

- brownie/_cli/run.py
- brownie/project/scripts.py
- tests/cli/test_cli_main.py
- tests/conftest.py
- tests/data/brownie-test-project/scripts/token.py
- tests/project/test_scripts.py
* better path management - handle multiple loaded projects
* cache imports, and reload modules that have already been imported
* add test cases
closes #252
> Updates to project.scripts

- brownie/project/main.py
> Delete stale compiler artifacts

- CHANGELOG.md
- brownie/project/compiler.py
- cache available solc compiler versions to avoid repeated calls, closes #265
> Solc version

- CHANGELOG.md
- brownie/_gui/opcodes.py
> highlight jumpdests within first 256 bytes

- CHANGELOG.md
- brownie/project/compiler.py
- tests/data/brownie-test-project/contracts/EVMTester.sol
- tests/network/transaction/test_revert_msg.py
- better error message for division by zero
> Zero division

- tests/cli/test_cli_ethpm.py
- tests/cli/test_cli_ethpm_release.py
- tests/cli/test_cli_main.py
Coverage was less in some test files for `_cli` tests.
Fixes #262 
Added more tests.
> Increases code coverage for _cli tests

- CHANGELOG.md
- brownie/project/compiler.py
- tests/data/brownie-test-project/contracts/EVMTester.sol
- tests/network/transaction/test_revert_msg.py
- tests/project/test_compiler.py
* error message for modulus by zero - closes #286 
* progress bar when installing new version of solc - closes #290
> Solc updates

- CHANGELOG.md
- brownie/_cli/__main__.py
- brownie/_cli/accounts.py
- docs/build-folder.rst
- docs/nonlocal-networks.rst
- tests/cli/test_cli_accounts.py
* Add `brownie accounts` to CLI - closes #253
> Add brownie accounts to CLI

- brownie/project/compiler/vyper.py
- tests/data/brownie-test-project/contracts/VyperTester.vy
Fixed #301 
`getattr` :)  I also added the failing code into `VyperTester.vy`, it isn't ever touched directly by a test but it's compiled for most of the tests in the suite.
> bugfix - vyper function calls and branch coverage

- brownie/_cli/compile.py
Added a note to `brownie compile` help that contracts automatically recompile.
> include note that contracts are automatically recompiled

- brownie/network/account.py
- brownie/network/contract.py
- brownie/network/transaction.py
- brownie/project/main.py
Remove the word "object" from various objects' `__repr__`.
> remove 'object' from repr

- brownie/project/main.py
- tests/project/main/test_main_project.py
Add `.gitignore` and `.gitattributes` when creating a new project - closes #298
> create .gitignore and .gitattributes when initializing new project

- CHANGELOG.md
- brownie/convert.py
- tests/main/convert/test_to_bytes.py
* allow `"0x"` and `""` to convert to bytes
* disallow booleans
* improve `TypeError` messages when converting
* add test cases
> Convert bytes bugfix

- CHANGELOG.md
- brownie/_cli/analyze.py
- brownie/_cli/ethpm.py
- brownie/_config.py
- brownie/data/brownie-config.yaml
- brownie/network/account.py
- brownie/network/alert.py
- brownie/network/contract.py
- brownie/network/transaction.py
- brownie/project/main.py
- brownie/project/scripts.py
- brownie/project/sources.py
- brownie/test/output.py
- brownie/utils/color.py
- docs/api-utils.rst
- docs/config.rst
- tests/main/test_config.py
- tests/utils/test_color.py
1. Remove the `colors` field from the config file.
2. Remove `__getitem__` style calls to `Color`.
3. Remove the intermediary copy of `brownie-config.yaml`, it was causing issues when config settings are changed in new releases.
Run the tests.
> Colors and config settings

- .gitignore
- docs/_static/css/custom.css
- docs/api-convert.rst
- docs/conf.py
Add a stylesheet to documentation to make them less painful for my eyes.
> add dark stylesheet to docs

- CHANGELOG.md
- brownie/_cli/analyze.py
- requirements.txt
- tests/cli/test_analyze.py
- complete refactor of the MythX plugin
- overhaul of the plugin's test suite
- enable AST submission for more precise results
- update analysis modes
> Update MythX analysis plugin

- CHANGELOG.md
- brownie/_cli/__main__.py
- docs/conf.py
- requirements.txt
- setup.cfg
- setup.py
> update dependency versions, changelog, bump version to 1.6.6

- CHANGELOG.md
- brownie/_cli/console.py
- brownie/network/account.py
- brownie/project/main.py
- docs/ethpm.rst
- requirements.txt
- tests/network/account/test_account_transfer.py
Various minor fixes:
- Allow transfer to unchecksummed hexstring address
- Color output for `dir` in console
- Ignore json files in contracts folder
- Update broken links in ethPM docs
- Bump `solcast` version
Run tests.
> Minor fixes

- brownie/_config.py
- brownie/data/brownie-config.yaml
- brownie/network/contract.py
- brownie/test/managers/base.py
- docs/config.rst
- tests/main/test_config.py
- tests/network/contract/test_contracttx.py
Make `pytest` config settings optional.
> make pytest config settings optional, remove from config file

- brownie/_config.py
Adjust how hypothesis' default settings are handled. The database is now always stored at `~/.brownie/hypothesis` which prevents warnings when running brownie from certain folders.
> fix hypothesis database location at ~/.brownie/hypothesis

- README.md
- docs/_static/css/custom.css
- docs/install.rst
Expand installation docs to recommend `pipx`.
Close #335
> docs: recommend pipx for installation

- brownie/test/__init__.py
- brownie/test/managers/runner.py
- requirements.txt
- tests/test/stateful/test_setup.py
Bump `hypothesis` dependency version to `5.8.0`.
> Hypothesis version bump

- brownie/project/sources.py
- brownie/test/output.py
Fix two bugs related to use of multiple projects at once.
1. Source highlights on contracts located outside of a project.
2. Coverage evaluation when tests touched contracts outside a project.
Thanks to @celioggr for bringing these to my attention.
> Bugfixes: multiple projects open

- docs/_static/css/toggle.css
- docs/_static/js/toggle.js
- docs/_templates/breadcrumbs.html
- docs/_templates/versions.html
> docs: move day/night toggle, make it more subtle

- brownie/data/default-config.yaml
- brownie/project/compiler/__init__.py
- brownie/project/ethpm.py
- brownie/project/main.py
- docs/api-brownie.rst
- docs/api-network.rst
- docs/compile.rst
- docs/config.rst
- docs/package-manager.rst
- docs/tests-hypothesis-property.rst
- tests/project/ethpm/test_create_manifest.py
Allow any settings to be passed to the solc optimizer - closes #405
Modifications to the shape of the config file.  See updated documentation.
Run tests.
> Allow full range of solc optimizer settings

- brownie/_config.py
- brownie/convert/utils.py
- brownie/network/account.py
- brownie/network/contract.py
- brownie/network/transaction.py
- tests/network/contract/test_contractcontainer.py
- tests/network/transaction/test_new_contracts.py
Various bugfixes and minor refactoring.
> Misc fixes and refactors

- brownie/_config.py
- brownie/project/main.py
- docs/config.rst
* Do not use config file to confim existence of a project.
* Load config file from home path if it exists.
> Config does not equal Project

- brownie/network/contract.py
- docs/api-network.rst
- tests/network/contract/test_contract.py
* add `as_proxy_for` kwarg to `Contract.from_explorer`
* convert `Contract.abi` and `Contract._name` to `@property` methods
> As proxy for

- brownie/_cli/console.py
- brownie/network/contract.py
- brownie/network/event.py
- brownie/utils/sql.py
Various last-minute minor fixes.
> Misc fixes

- CHANGELOG.md
- brownie/_cli/__main__.py
- docs/conf.py
- setup.cfg
- setup.py
* update changelog
* bump version to `1.7.0`
> update changelog, bump version

- brownie/network/contract.py
Add `_autosuggest` method to `ContractCall`
> fix: add _autosuggest to ContractCall

- brownie/_cli/networks.py
- brownie/_config.py
> fix: spelling mistakes

- brownie/project/compiler/solidity.py
- tests/network/transaction/test_revert_msg.py
Fix an issue with dev revert strings, when the final revert is caused by `require(false);`
> Dev revert fix

- CHANGELOG.md
- brownie/_cli/__main__.py
- docs/conf.py
- setup.cfg
- setup.py
Update changelog, bump version to `v1.7.1`
> changelog, bump version to v1.7.1

- CHANGELOG.md
- brownie/_cli/__main__.py
- docs/conf.py
- setup.cfg
- setup.py
> chore: update changelog, bump version to v1.7.3

- CHANGELOG.md
- brownie/network/contract.py
- tests/network/contract/test_contract.py
- Do not repeat queries for unverified source
- fix `KeyError` when using `autofetch_sources`
Run tests.
> Autofetch fixes

- brownie/_gui/report.py
- brownie/_gui/root.py
Update the GUI to understand the new pathMap system applied in `v1.7.0`
> fix: apply pathMap when displaying GUI reports

- brownie/test/fixtures.py
- docs/api-test.rst
- docs/tests-pytest-fixtures.rst
Add a session scoped fixture to access the  `Contract` class.
Closes #452
> Contract fixture

- brownie/_cli/console.py
- brownie/test/managers/runner.py
Expose local variables when using interactive mode during testing.
Digging around in pytest internals.
Run tests.
> Pytest locals

- brownie/test/managers/runner.py
Expose globals in the pytest interactive console.
* obtain globals from `call.excinfo.traceback[-1].frame.f_globals`
* filter pytest internal, python interals, and test functions
* load the console in debugging mode
> feat: expose global namespace in pytest interactive console

- brownie/convert/datatypes.py
- brownie/convert/utils.py
- tests/convert/test_return_value.py
Fix an issue when decoding arrays of tuples.  Fixes #513 
Expand the logic around tuples to also consider arrays.
Run tests. I added some new cases.
> Fix tuple arrays

- brownie/_cli/console.py
Properly handle multi-statement pastes in the console
Closes #516 
Add a custom key binding for the `BracketedPaste` that swaps the compile mode from `single` to `exec`.
Run the console.
> fix: allow multiple command pastes in console

- brownie/test/coverage.py
- brownie/test/managers/base.py
- brownie/test/managers/master.py
- brownie/test/managers/runner.py
- requirements-dev.txt
- requirements.txt
Add docstrings and comments for Brownie's pytest plugin and coverage evaluation logic.
Closes #458
> `brownie.test` docstrings and comments

- brownie/_cli/run.py
- tests/cli/test_cli_main.py
Add the `--interactive` flag to `brownie run`
Closes #520
> Add interactive flag to brownie run

- codecov.yml
Added a `codecov.yml` file which will make status checks informational and non-blocking
Closes #559 
I added a codecov.yml file which makes status checks informational as documented here: https://docs.codecov.io/docs/commit-status#informational
We will see the status checks from this PR
> Add codecov yaml to prevent failing status checks

- codecov.yml
Adjust codecov settings to avoid the comments and failed checks from lack of coverage.
Closes #559
> Adjust codecov config settings

- .github/workflows/main.yaml
- tox.ini
Move the check for external doc links to it's own job and mark that job as experimental.
If this PR shows as passing all checks, it worked.
> Ci external doctest

- brownie/_config.py
- brownie/test/managers/base.py
- brownie/test/plugin.py
More improvements to hypothesis related output:
* When `-v` is used, also enable verbose mode in hypothesis.
* Apply custom formatting to stdout output during verbose mode.
Related issue: #567 
Run some tests, look at the output
> hypothesis output round 2

- brownie/network/web3.py
- docs/init.rst
- docs/tests-hypothesis-property.rst
- tests/network/contract/test_contract.py
- tests/test/strategies/test_address.py
Fix the flaky tests.
Magic!!!  Just kidding..  a few simple fixes, one test marked as flaky that we'll deal with in `v2` Soon:tm:
Run tests, enjoy checkmarks.
> Fix flaky tests

- brownie/exceptions.py
Improve `VirtualMachineException` logic to handle reverts from Parity.
Connect to Kovan and do something to trigger a revert.
> Error handling when using parity

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- docs/install.rst
- docs/tests-hypothesis-stateful.rst
Fix various links to point at `eth-brownie/brownie` instead of `iamdefinitelyahuman/brownie`
> doc: update urls in docs, changelog, readme

- docs/config.rst
> Update config.rst - Fix typo

- brownie/_cli/run.py
exit `brownie run` with non-zero status on exception
> exit `brownie run` with non-zero status on exception

- brownie/project/compiler/solidity.py
Handle solc source maps that are too long.
Related to https://github.com/eth-brownie/brownie/pull/676
Check the length of the bytecode without metadata, and do not evaluate the source map beyond that length.
Run tests.
> fix: handle solidity source maps that are too long

- docs/tests-hypothesis-stateful.rst
* update vyper syntax to use `0.2.x`
* add more examples of projects using stateful testing
> Update stateful testing documentation

- brownie/_cli/__main__.py
Add a `--version` flag in the CLI
Closes #702 
```
brownie --version
```
> feat: add version flag

- brownie/project/sources.py
Fix an issue when a source file contains multiple pragma statements.
> fix: multiple pragma statements

- .github/workflows/main.yaml
- README.md
- brownie/network/transaction.py
- docs/install.rst
Support for ganache v6.10.1
Closes #711 
* Re: #562, only shift the gas costs if the first step has a cost > 21000.
* bump the ganache version in the CI
* bump the recommended / "tested against" version in the readme and docs
Run tests.
> Ganache 6.10.1

- brownie/network/contract.py
Patches:  #718
Intercept, and added a warning
Write a test that uses it
> Allow overwriting the balance member if a contract defines it

- brownie/_cli/compile.py
* add a `--size` flag when using `brownie compile` to view deployed bytecode sizes
> Size flag for brownie compile

- brownie/network/contract.py
Improve exception message for `AttributeError` on a contract.
> style: improve AttributeError for contracts

- brownie/convert/datatypes.py
Add ` __hash__` function to `EthAddress` to make it hashable.
> fix: make ethaddress hashable

- brownie/network/transaction.py
- brownie/test/output.py
* handle a case where there is no input or calldata when expanding trace
* handle missing data in the coverage map
> Trace fixes

- brownie/project/compiler/solidity.py
Fix an issue when finding the offset for a nonpayable function.
> fix: revert offset

- brownie/_cli/compile.py
* fix an issue when using `brownie compile --size` and one of the contracts exceeds the EIP 170 limit.
> fix: bytecode size > limit

- docs/package-manager.rst
Updated docs to fix reference from `brownie pm export` to `brownie pm clone` 
Fixes #769 
- [X ] I have confirmed that my PR passes all linting checks
- [X ] I have updated the documentation
> doc update to remove export & add clone

- brownie/_cli/test.py
Allow arbitrary flags when in `brownie test`.
Closes #560
> cli: generalize argv handling for brownie test

- brownie/network/contract.py
Add support for multi-file etherscan source format.
> feat: support etherscan multi-file source format

- .github/workflows/main.yaml
- README.md
- docs/core-accounts.rst
- docs/core-contracts.rst
- docs/install.rst
* Bump ganache version to `v6.11.0` in CI and installation docs
* Add documentation for unlocking arbitrary accounts
Closes #758
> Unlocking arbitrary accounts, round 2

- brownie/_cli/compile.py
Allow force-compile of specific contracts using `brownie compile`.
> Allow force-compile of specific contracts via cli

- brownie/network/account.py
> Fix z typo gasPrce -> gasPrice

- brownie/convert/datatypes.py
- tests/convert/test_return_value.py
Add a `__ne__` method to `ReturnValue`.
Run the test suite.
> Add `__ne__` to `ReturnValue`

- brownie/network/transaction.py
Show the nonce of a tx in the stdout output.
> feat: show nonce in pending tx output

- brownie/network/state.py
- docs/api-network.rst
- docs/core-chain.rst
- tests/network/state/test_blocks.py
Add a `timedelta` kwarg to `chain.time`.
This is a continuation of #844
Run tests.  I've added new test cases.
> Add `timedelta` to `chain.mine`

- brownie/network/transaction.py
During `@trace_method` property methods, do not raise 
Fixes an issue introduced in #853, as reported by @banteg
Move the `RPCRequestError` raise into a try:catch block, and perform the actual check against `web3.supports_traces` when querying the trace.  This way attributes that only sometimes need the trace aren't blocked unnecessarily.
> fix: trace methods that only require trace in certain conditions

- README.md
> feat: added docs on how to run master with pipx

- brownie/network/contract.py
Check for proxy contracts using [EIP 1967](https://eips.ethereum.org/EIPS/eip-1967) during `Contract.from_explorer`.
If `as_proxy_for` is `None`, query the eip1967 implementation storage slot and if non-zero, assume a proxy.
> check for eip1967 proxy implementation

- brownie/network/contract.py
Add `info`, `decode_input` and `decode_output` to overloaded methods.
> Feat overloaded methods

- brownie/network/transaction.py
Finish implementing #926 
Run tests.
> fix: don't automatically decode events from txreceipt

- docs/tests-pytest-intro.rst
> closing the parenthesis

- docs/package-manager.rst
Related issue: #840 
verified export command did not work and clone command did
install package, try to export it, doesn't work, try to clone it, works. 
- [✅] I have confirmed that my PR passes all linting checks
- [✅] I have updated the documentation
> changed export command to clone in documentation - issue 840

- brownie/_cli/run.py
- brownie/project/scripts.py
When using the `--interactive` flag with `brownie run`, open the console with the local variables from the frame of the function that was executed.
A bunch of voodoo.  It's fairly well explained in the comments.
Try it!
> Access function frame when using `run`

- brownie/project/scripts.py
Fix an issue preventing the console from opening when using `brownie run -i` and a script raises.
Closes #986 
The initial issue came from line 90 - the filename wasn't properly being set when calling `compile`, so brownie interpreted any exceptions raised here as being "internal".
Once I fixed that, a new issue became apparent - the AST mutations were causing issues with the source offsets. So I did a bit more voodoo and now it seems to work nicely.
> fix: interactive mode in brownie run

- brownie/network/transaction.py
Fix an issue catching dev revert comments on the "optimizer revert" (#907)
The problem was when the revert happens on the optimizer revert, and this is the _actual_ failing instruction.  It didn't start to manifest until 0.8.2 but I'm unsure what changed in that release to make it appear.
> fix: optimizer revert

- brownie/data/network-config.yaml
- brownie/network/contract.py
- tests/cli/test_cli_networks.py
- tests/network/contract/test_contract.py
> BSC support

- CHANGELOG.md
- docs/config.rst
Closes #1039
- [] I have included test cases
> fixed docs typo

- requirements-dev.txt
- requirements-windows.txt
- requirements.txt
Bump `urllib3` to `v1.26.5` - fixes https://github.com/advisories/GHSA-q2q7-5pp4-w6pg
> bump urllib3 to v1.26.5

- docs/network-management.rst
Add small section on native EVM compatible chain support to the docs. Lists current native integrations, and what is required to enable native integration.
Fixes: #934
> docs: native support for EVM compatible chains

- docs/api-network.rst
Fix typo
Fixed a typo
Fixed a typo
See docs
- [NA] I have confirmed that my PR passes all linting checks
- [NA] I have included test cases
- [Y] I have updated the documentation
- [NA] I have added an entry to the changelog
> docs: fix typo in api-network.rst

- brownie/network/transaction.py
> fix: do not assume language exists

- brownie/convert/datatypes.py
- brownie/network/account.py
- brownie/network/transaction.py
- brownie/project/compiler/vyper.py
- requirements-dev.txt
- requirements-windows.txt
- requirements.in
- requirements.txt
Bump all dependencies.
`pip-compile -U requirements.txt`
> chore: bump deps

- brownie/network/gas/strategies.py
Add a kwarg `max_gas_price` for scaling gas price strategies. This provides some safety on long-running scripts in case of a sudden spike in gas costs.
> Add max gas price for scaling strategies

- .github/workflows/core-ganache.yaml
- .github/workflows/evm.yaml
- .github/workflows/functionality.yaml
- .github/workflows/lint.yaml
- tests/conftest.py
- tests/network/account/test_accounts.py
- tests/network/rpc/conftest.py
- tests/network/test_main_network.py
- tests/network/transaction/test_required_confirmations.py
- tests/project/ethpm/test_create_manifest.py
- tests/project/test_brownie_config.py
- tox.ini
* Split the CI into multiple workers.
* Generalize the test suite so it can target different development networks
This is laying groundwork for testing #1043 
Pray to god the CI passes for once.
> Split CI into multiple workflows

- brownie/network/account.py
Made it possible to save an account with a specified password
added a kwarg to save.
> Allow specifying password when saving an account

- brownie/network/contract.py
add ftmscan apy key.
using the same lines what was used for other networks.
I install this version in my computer and I stop getting the rate limiting error
> add FTMSCAN APY key

- brownie/network/multicall.py
Add a lock when flushing the multicall pending call queue, to resolve concurrency bug
Added a lock around the part that swaps the bytecodes
Run this script
```python
from brownie import multicall, ZERO_ADDRESS, Contract
from concurrent.futures import ThreadPoolExecutor
factory = Contract('0xB9fC157394Af804a3578134A6585C0dc9cc990d4')
def get_pools():
with multicall:
pools = [factory.pool_list(i) for i in range(int(factory.pool_count()))]
return pools
def get_balances(pool):
with multicall:
coins = factory.get_coins(pool)
balances = factory.get_balances(pool)
decimals = factory.get_decimals(pool)
return {
coin: balance / 10 ** dec
for coin, balance, dec in zip(coins, balances, decimals)
if coin != ZERO_ADDRESS
}
def main():
pools = get_pools()
datas = …
```
> fix: add lock when flushing the pending call queue Multicall

- brownie/data/network-config.yaml
- brownie/network/contract.py
* add multicall2 for arbitrum
* add support for `$ARBISCAN_TOKEN` (and generalize logic here for the future)
> Arbitrum updates

- docs/core-gas.rst
Noticed an incorrect import in the docs
> Fix import in documentation

- CHANGELOG.md
- brownie/network/contract.py
Add support for `ARBISCAN_TOKEN`
> Add support for `ARBISCAN_TOKEN` env var

- brownie/data/network-config.yaml
- brownie/network/contract.py
* Add the avax c-chain to default networks
* Add support for snowtrace
Closes #1329
> Support for Avalanche

- brownie/data/network-config.yaml
Added Optimistic Ethereum network configuration to `network-config.yaml`.
Related issue: #1151
> feat: add Optimism to network config

- tests/project/main/test_main_project.py
Fix lint error on main branch
Remove unused import
Run linter
> Fix lint error

- brownie/data/network-config.yaml
- brownie/network/contract.py
- Add Aurora to default networks
- Add support for aurorascan
> Support for Aurora

- docs/tests-pytest-intro.rst
Just a small error in the docs
> Fix small error in tests-pytest-intro.rst

- brownie/data/network-config.yaml
Added Boba Network support. [boba.network](https://boba.network/)
Added Boba to the networks file.
Add Bobanetwork to brownie and run e.g. script.
> feat: add boba

- docs/api-network.rst
I have corrected typos in api-network.rst
> docs: fixed some typos

- brownie/network/contract.py
Add support for [0xSplits Clones](https://github.com/0xSplits/splits-contracts/blob/main/contracts/libraries/Clones.sol#L32) minimal proxies.
Check `Contract(addr)` with any of [these addresses](https://etherscan.io/find-similar-contracts?a=0x42ACFd8f410F5c19f24e3cF703acc7f637390Be9&lvl=5).
> feat: detect 0xsplits clones proxies

- brownie/data/network-config.yaml
This PR adds the Moonbase Alpha TestNet and Moonriver to the network configurations.
> add moonbase alpha and moonriver to networks

- brownie/network/contract.py
Added https://moonscan.io/ , https://moonriver.moonscan.io/ support
Added `moonscan` into `_explorer_tokens ` dict
Add moonriver/moonbeam network to brownie and run e.g. contract source code verification
> feat: add moonriver/moonbeam explorer

- brownie/project/compiler/vyper.py
A proper fix for #1546 
When mapping the sourceMap to the AST, do not assume that there is a 1:1 relationship between ast nodes and source offsets. As of vyper `v0.3.3` this assumption no longer holds.
> fix: vyper pcMap generation, better solution

- docs/compile.rst
- docs/package-manager.rst
> Fix: typos

- brownie/data/network-config.yaml
> fix: swap optimism testnet from kovan to goerli

- brownie/_cli/run.py
- brownie/utils/docopt.py
* bump local version of `docopt-ng` to `v0.9.0` (edits for compatibility / linting)
* remove use of deprecated `more_magic` flag
This is necessary because the previous docopt version was failing on python 3.12
> Docopt-ng updates

- brownie/network/rpc/anvil.py
Related issue: https://github.com/eth-brownie/brownie/issues/1686
Add more arguments from the output of `anvil --help`
> feat(rpc/anvil): add  more anvil command line args

- CHANGELOG.md
- brownie/network/contract.py
added blastscan explorer and to supported explorers
added blast explorer and chain to _explorer_tokens variable.
> Support blastscan verification

- brownie/network/event.py
> fix: ds-note decoding

- README.md
- brownie/project/main.py
Fixed a couple of typos:  
- In `README.md`, corrected `lastest` to `latest`.  
- In `main.py`, corrected `aleady` to `already`.  
Hope this improves clarity. 🙂
> chore: fix typos

- docs/api-brownie.rst
- docs/api-network.rst
This pull request contains changes to improve clarity, correctness and structure.
> fix: typos in documentation files

- brownie/network/main.py
- brownie/network/middlewares/geth_poa.py
- brownie/test/managers/runner.py
hey team! I found duplicate words and fixed them.
> docs: remove consecutive duplicate words

- .github/workflows/core-ganache-3.10.yaml
- .github/workflows/core-ganache-3.11.yaml
- .github/workflows/core-ganache-3.12.yaml
- .github/workflows/evm.yaml
- .github/workflows/functionality.yaml
replace deprecated actions/cache@v2 with v4
> fix(cicd): replace deprecated actions/cache@v2 with v4

- brownie/convert/datatypes.py
- brownie/convert/utils.py
- brownie/network/account.py
- brownie/network/contract.py
- brownie/network/transaction.py
- brownie/project/main.py
- brownie/utils/color.py
- brownie/utils/docopt.py
> chore: refactor with f-strings

- brownie/convert/datatypes.py
- brownie/convert/normalize.py
- brownie/network/event.py
> feat: optimize format_event

- brownie/network/gas/strategies.py
- brownie/network/middlewares/catch_tx_revert.py
- brownie/network/middlewares/ganache7.py
- brownie/network/middlewares/hardhat.py
- brownie/utils/docopt.py
> feat: use set when checking group membership with literals

- brownie/_gui/bases.py
- brownie/_gui/report.py
- brownie/_gui/root.py
- requirements.txt
> chore: refactor gui

- brownie/project/compiler/solidity.py
- brownie/project/compiler/vyper.py
- requirements.txt
> chore: refactor compilers

- brownie/_cli/console.py
- brownie/_cli/networks.py
- brownie/_cli/pm.py
- brownie/_cli/test.py
> chore: refactor cli

- brownie/utils/docopt.py
- brownie/utils/output.py
- brownie/utils/sql.py
- brownie/utils/toposort.py
- requirements.txt
> feat: optimize utils

- brownie/network/middlewares/catch_tx_revert.py
- brownie/network/middlewares/ganache7.py
> chore: refactor middlewares

- brownie/project/build.py
- brownie/project/flattener.py
- brownie/project/main.py
- brownie/project/scripts.py
- brownie/project/sources.py
- requirements.txt
> chore: refactor project

- tests/network/rpc/test_attach.py
> fix(test): fix dockerized test mock patches

- .github/workflows/pip-compile.yaml
- brownie/_gui/report.py
- brownie/_gui/root.py
- brownie/network/event.py
- brownie/project/compiler/solidity.py
- brownie/project/compiler/vyper.py
- brownie/project/flattener.py
- brownie/project/main.py
- brownie/utils/docopt.py
- requirements.txt
> feat(cicd): `black .` github runner

- requirements.txt
- tests/conftest.py
- tests/network/contract/test_contract.py
- tests/network/contract/test_ens_contract.py
- tests/network/contract/test_interface.py
- tests/network/contract/test_persistence.py
- tests/network/state/test_get_transaction.py
> feat(test): connect_to_mainnet shared fixture

- requirements.txt
- tests/conftest.py
- tests/network/transaction/test_revert_msg.py
> fix(test): fix test_deployment_size_limit string matching

- requirements.txt
- tests/conftest.py
- tests/network/test_main_network.py
> fix(test): fix test_gas_limit_auto

- requirements.in
- requirements.txt
- tests/network/test_web3.py
> fix: InvalidPointer from eth-abi

- .github/workflows/pip-compile.yaml
- requirements-dev.in
- requirements-dev.txt
- tests/network/account/test_ens_account.py
- tests/network/contract/test_contract.py
- tox.ini
Since some tests experience intermittent failures, I used [eth-retry's decorator](https://github.com/BobTheBuidler/eth_retry/) to wrap those tests so they automatically retry and turn green unless they are actual failing test cases.
> fix(test): retry tests on intermittent errors

- brownie/_config.py
- brownie/_expansion.py
- brownie/exceptions.py
- brownie/network/contract.py
- brownie/network/main.py
- brownie/network/multicall.py
- brownie/network/rpc/ganache.py
- brownie/network/state.py
- brownie/network/transaction.py
- brownie/network/web3.py
> chore: refactor

- brownie/test/managers/base.py
- brownie/test/managers/runner.py
- brownie/test/output.py
- brownie/test/plugin.py
- brownie/test/stateful.py
- tests/network/contract/test_persistence.py
> chore: refactor test

- brownie/network/contract.py
- requirements-dev.txt
- requirements.txt
* updated etherscan API to use V2
> Etherscan v2 API

- requirements.txt
- setup.py
> chore: bump eth-event

- requirements.in
- requirements.txt
> fix: pin eth-typing to fix web3

- brownie/network/contract.py
- requirements.txt
Fixed the 4 linting errs from #1852 
> chore: lint

- tests/network/test_web3.py
> fix(test): network.connect race cond in test_mainnet

- tests/network/test_main_network.py
> fix(test): fix long running tests due to unsuccessful retries on goerli

- brownie/network/contract.py
- brownie/project/compiler/__init__.py
it does too many checks internally and is quite wasteful for our purposes
> chore: refactor out remove_0x_prefix

- tests/network/test_main_network.py
> fix(test): disable test_gas_price_auto (goerli is ded)

- brownie/utils/__init__.py
- brownie/utils/color.py
- setup.py
> feat: compile utils/color.py

- requirements-dev.txt
- requirements.in
- requirements.txt
- tests/conftest.py
- tox.ini
> fix(test): include setuptools in test deps to fix web3py

- brownie/convert/datatypes.py
- brownie/convert/main.py
- brownie/network/account.py
- brownie/network/contract.py
- requirements.in
- requirements.txt
> feat: implement faster-eth-utils

- brownie/_cli/__main__.py
- brownie/_cli/accounts.py
- brownie/_cli/console.py
- brownie/_cli/networks.py
- brownie/convert/main.py
- brownie/convert/normalize.py
- brownie/convert/utils.py
- brownie/network/__init__.py
- brownie/network/account.py
- brownie/project/compiler/utils.py
- brownie/utils/__init__.py
- brownie/utils/_color.py
- brownie/utils/color.py
- brownie/utils/sql.py
- brownie/utils/toposort.py
- pyproject.toml
- setup.py
_cli
convert
project/compiler
utils/output.py
utils/sql.py
utils/toposort.py
> feat: compile half the lib to C

- brownie/_cli/console.py
- brownie/_cli/gui.py
- pyproject.toml
> Bob the buidler patch 5

- requirements-dev.txt
- requirements.txt
> chore: pip-compile

- pyproject.toml
- requirements-dev.txt
- requirements.txt
- tests/network/account/test_ens_account.py
> chore: bump [tool.black] target version

- brownie/convert/main.py
- brownie/project/compiler/solidity.py
- setup.py
> feat: BROWNIE_NOCOMPILE env var to make C compilation optional

- brownie/convert/datatypes.py
- brownie/convert/normalize.py
- brownie/convert/utils.py
- brownie/network/contract.py
- brownie/network/event.py
- brownie/typing.py
- build/__native_internal_67ba59a4b46c20ffa2b1.h
- requirements-windows.txt
- requirements.txt
> feat(mypy): implement typed dicts from web3 and eth-typing

- Dockerfile
> chore: bump python version in dockerfile

- brownie/exceptions.py
- setup.py
> chore: use @final for exceptions

- brownie/project/compiler/solidity.py
- brownie/project/compiler/vyper.py
- build/__native_internal_42291a5fc61d44f940da.h
> feat: update evm versions for solidity and vyper

- brownie/network/contract.py
- brownie/project/build.py
- brownie/project/compiler/__init__.py
- brownie/project/compiler/solidity.py
- brownie/project/compiler/utils.py
- brownie/project/compiler/vyper.py
- brownie/project/main.py
- brownie/project/sources.py
- brownie/typing.py
- build/__native_42291a5fc61d44f940da.h
- build/__native_internal_42291a5fc61d44f940da.h
- tests/network/state/test_get_transaction.py
> feat(mypy): more typing enhancements

- brownie/_config.py
- brownie/_expansion.py
- brownie/network/contract.py
- brownie/project/build.py
- brownie/project/compiler/__init__.py
- brownie/project/compiler/solidity.py
- brownie/project/main.py
- pyproject.toml
> feat: microoptimize attr lookups

- brownie/convert/datatypes.py
- brownie/network/alert.py
- brownie/network/transaction.py
- brownie/project/main.py
- requirements-dev.txt
- requirements.txt
- setup.py
- tests/project/test_sources.py
> feat: compile network/alert.py

- brownie/convert/datatypes.py
> fix: TypeError when calling EthAddress with Contract type input

- brownie/project/build.py
- requirements.txt
> fix: type error in Build._add_contract

- brownie/_config.py
- brownie/network/state.py
- brownie/project/compiler/solidity.py
- brownie/typing.py
> feat(mypy): more typing stuff

- brownie/project/compiler/vyper.py
- brownie/typing.py
- build/__native_b231d8a45f8022bf8159.h
- build/__native_internal_b231d8a45f8022bf8159.h
> feat(mypy): VyperAstNode typed dict

- brownie/network/middlewares/__init__.py
- brownie/network/middlewares/_setup.py
- brownie/network/middlewares/caching.py
- brownie/network/middlewares/catch_tx_revert.py
- brownie/network/middlewares/ganache7.py
- brownie/network/middlewares/geth_poa.py
- brownie/network/middlewares/hardhat.py
- build/__native_b5e4b1180acefab623dd.h
- build/__native_internal_b5e4b1180acefab623dd.h
> fix: TypeError in middleware setup

- brownie/network/state.py
> fix: TypeError in _get_deployment

- .github/workflows/pip-compile.yaml
- requirements-dev.txt
- requirements-windows.txt
- requirements.txt
> feat(cicd): update windows deps in pip compile workflow

- brownie/project/compiler/__init__.py
- brownie/typing.py
- build/__native_internal_b5e4b1180acefab623dd.h
> fix: add 'interfaces' key to InputJson typed dicts

- brownie/network/web3.py
- brownie/project/compiler/__init__.py
- brownie/project/compiler/solidity.py
- brownie/test/stateful.py
- requirements-dev.txt
> chore: `black .`

- pyproject.toml
> chore: include eth-typing in build deps

- pyproject.toml
- requirements-dev.txt
- requirements-windows.txt
- requirements.txt
> chore: include eth-event in build deps

- .github/workflows/pip-compile.yaml
- brownie/project/compiler/solidity.py
- brownie/project/compiler/vyper.py
- brownie/test/output.py
- brownie/typing.py
- build/__native_b5e4b1180acefab623dd.h
- build/__native_internal_b5e4b1180acefab623dd.h
> feat(mypy): CoverageMap typed dict

- .github/workflows/pip-compile.yaml
- brownie/network/contract.py
- brownie/network/event.py
- brownie/typing.py
- build/__native_internal_b5e4b1180acefab623dd.h
- tox.ini
> feat(mypy): more type hints in contract.py

- brownie/project/compiler/solidity.py
- brownie/project/compiler/vyper.py
- brownie/typing.py
> fix(mypy): mark ProgramCounter fields with NotRequired

- brownie/network/account.py
> fix: TypeError in _add_to_undo_buffer subthread

- brownie/exceptions.py
> fix: TypeError in _get_dev_revert

- brownie/project/scripts.py
- requirements-dev.txt
- requirements-windows.txt
- requirements.txt
> fix: TypeError in _get_ast_hash

- brownie/network/state.py
- brownie/project/main.py
- build/__native_b5e4b1180acefab623dd.h
- build/__native_internal_b5e4b1180acefab623dd.h
> fix: TypeError due to json.dumps tuple handling

- brownie/network/event.py
- brownie/network/state.py
- brownie/network/transaction.py
- brownie/utils/hex.py
fix some minor issues in comments
> chore: fix some minor issues in comments

- docs/core-contracts.rst
- docs/core-gas.rst
- docs/gui.rst
- docs/python-package.rst
- docs/tests-pytest-intro.rst
> chore: fix some typos for rst file

- .github/workflows/compile.yaml
- .github/workflows/pip-compile.yaml
> fix(cicd): repo chores gh action when PR is from fork

- .github/workflows/compile.yaml
> fix(cicd): checkout working branch before push
