eth-brownie/brownie

README.md
If you have "brownie:1" in the build command, the image that results is tagged as brownie:1.
The run command doesn't specify brownie:1 so docker looks for brownie:latest, which doesn't exist.  This PR removes the 1. Alternately you could add the :1 to the run command.
=> Update docker tag

CHANGELOG, brownie/__init__.py, brownie/convert.py, brownie/exceptions.py, brownie/network/account.py, brownie/network/alert.py, brownie/network/contract.py, brownie/network/history.py, brownie/network/rpc.py, brownie/network/transaction.py, docs/api-brownie.rst, docs/api-network.rst, tests/network/account/test_account_deploy.py, tests/network/contract/test_contract.py, tests/network/contract/test_contractconstructor.py, tests/network/contract/test_multiple_projects.py, tests/network/rpc/test_weakref.py, tests/network/transaction/test_attributes.py, tests/network/transaction/test_trace.py
* create `Contract` instances using only ABI, closes #160 
* properly handle unknown contracts when expanding transaction traces
* simplify callback on contract deployment
* update tests and docs
=> Unknown contract

brownie/exceptions.py, brownie/network/event.py, docs/api-brownie.rst, tests/brownie-test-project/contracts/BrownieTester.sol, tests/network/test_event.py
`eth-event` appends ` (indexed)` to the indexed keys names that could not be decrypted.  This change modifies `EventDict` and `_EventItem` so that those event keys can still be queried without including indexed, and improves the exception verbosity when a key isn't found.
=> expand EventDict and _EventItem __getitem__

brownie/project/main.py, docs/compile.rst, docs/tests.rst
Adds documentation about format of `build/tests.json`
=> add test.json info in docs

.github/ISSUE_TEMPLATE.md, brownie/_config.py, brownie/data/config.json, brownie/network/account.py, docs/config.rst, docs/tests.rst, tests/network/account/test_account_transfer.py
Fixed https://github.com/iamdefinitelyahuman/brownie/issues/184
* catch exceptions raised when gas estimation fails from a reverting tx
* change config: `broadcast_reverting_tx` -> `reverting_tx_gas_limit`
=> Estimate gas fix

brownie/convert.py, tests/convert/test_return_value.py
Allow `ReturnValue` to be hashable
Closes https://github.com/iamdefinitelyahuman/brownie/issues/182
=> hashable ReturnValue

docs/nonlocal-networks.rst, docs/toctree.rst
Connecting to and interacting with non-local networks is not clearly documented - referenced in issue #174 
Fixes #174 by adding new section to documentation that explains how to leverage Brownie to interact with non-local Ethereum networks.
=> Add non-local networks section

brownie/_cli/analyze.py, brownie/network/transaction.py
* fix f-string in brownie analyze
* properly display "transaction" when tx is not a contract call
=> Cli verbosity bugfixes

docs/api-network.rst, docs/interaction.rst, docs/quickstart.rst
Incorrect syntax in examples for `Contract.deploy`
Corrected the examples. Closes #239
=> fix syntax for Contract.deploy examples

CHANGELOG.md, brownie/_cli/console.py, brownie/utils/color.py
Pretty printing of some dicts and sequences has been broken in the console since migrating to `InteractiveConsole`.
- pretty printing for more objects in the console
- properly display `SyntaxError` in console when there is no source highlight
=> Console color fixes

brownie/network/rpc.py, docs/test-rpc.rst
Filename parameters to dump private keys on running ganache-cli. Can be useful when connecting to Ganache from an external Dapp.
Added in rpc.py
=> Dumping private keys when loading ganache-cli on specificied filename.

setup.py
The development status classifier in setup.py seems to be out of date and does not reflect the fact that brownie is now out of beta.
I changed the development status to "Development Status :: 5 - Production/Stable" in setup.py.
=> Update Development Status to production/stable in setup.py

CHANGELOG.md, brownie/__init__.py, brownie/_cli/analyze.py, brownie/_cli/console.py, brownie/network/__init__.py, brownie/network/contract.py, tox.ini
Tkinter is an unnanounced but required dependency.
Adjusted imports and use `importlib` to avoid importing `brownie._gui` except when the user explicitely requests to load the Gui.
Fixes #247
=> remove tkinter dependency when not loading GUI

CHANGELOG.md, brownie/exceptions.py, brownie/network/account.py, brownie/network/transaction.py, brownie/project/build.py, brownie/project/compiler.py, tests/data/brownie-test-project/contracts/EVMTester.sol, tests/network/transaction/test_attributes.py, tests/network/transaction/test_revert_msg.py
- allow `dev:` revert comments for `assert` statements
- better error messages when sending ether to nonpayable function, or trying to access an invalid array index
closes #237 
closes #255 
closes #256
=> revert verbosity improvements

tests/cli/test_cli_main.py
Refers: #262 
test_cli_main.py had CliTester class implemented performing functions similar to monkeypatch.setattr etc.
The class functionalities were replaced with `monkeypatch.setattr` and `mocker.spy`.
=> Replaces CliTester functionalities with monkeypatch and mocker.spy

brownie/_config.py, brownie/data/brownie-config.yaml, brownie/project/compiler/__init__.py, brownie/project/compiler/solidity.py, brownie/project/ethpm.py, brownie/project/main.py, docs/compile.rst, docs/config.rst, tests/project/compiler/test_solidity.py, tests/project/compiler/test_vyper.py
* reorganize the config file, `evm_version` and `minify_source` are not specific to `solc`
* do not require `solc` settings when a project has no solidity contracts - closes #297
* do not install `solc` until needed for compilation (previously it was done as soon as the config file was read)
* fix ethPM / vyper issues that were missed in #294
* updates to tests and documentation
=> Solc compiler edits and fixes

brownie/network/rpc.py
On OSX, brownie was failing with `psutil.AccessDenied` when ganache was already running.  This was a result of how OSX handles permissions for viewing process connections.
Instead of calling `psutil.net_connections`, check the connections of each active process individually and handle the `AccessDenied` exception.
Confirmed working on OSX 10.13
Closes #263
=> Bugfix - attaching to existing RPC process on OSX

brownie/_cli/accounts.py
`~/.brownie/accounts` is never created when accessing the `brownie accounts` cli functionality. This can lead to a lot of errors with paths not existing.
Create the path whenever `brownie accounts` is called, if it does not exist.
=> bugfix: ensure accounts data subfolder exists

brownie/_config.py, brownie/network/rpc.py, brownie/project/compiler/solidity.py, docs/compile.rst, docs/config.rst, tests/network/rpc/test_evm.py, tests/project/compiler/test_solidity.py
* Allow use of `atlantis` and `agharta` in the config file.
=> Add Ethereum Classic rulesets

brownie/data/brownie-config.yaml, tests/main/test_config.py
RPC Public endpoints for ETC and Kotti Testnet
Add them to config file so it makes the tutorial I'm working on for Brownie easier to do.
=> feat: Add ETC and Kotti RPC endpoints to config

brownie/data/brownie-config.yaml, brownie/network/account.py, brownie/network/main.py, docs/api-network.rst, docs/config.rst, tests/network/account/test_account_deploy.py, tests/network/account/test_account_transfer.py, tests/network/contract/test_contractconstructor.py, tests/network/contract/test_contracttx.py
* Modify default `gas_price` for development network to zero.
* Change `gas_price` and `gas_limit` from bools to `auto` to be more explicit.
Closes #315
* Changes to how the config settings are evaluated in `brownie/network/account.py`
* Updated defult config file
Run the tests.  I added some new test cases and modified existing ones to verify these changes.
=> Use zero gas price on development network

.travis.yml, CHANGELOG.md, README.md, brownie/data/brownie-config.yaml, brownie/network/rpc.py, brownie/project/compiler/__init__.py, docs/api-network.rst, docs/compile.rst, docs/config.rst, docs/install.rst, docs/test-rpc.rst, tests/conftest.py, tests/network/rpc/test_evm.py, tests/project/compiler/test_vyper.py
* Set `istanbul` as default EVM ruleset
* Update test cases
* Bump tested `ganache-cli` version to 6.8.2
Closes #276 
Run the tests.  EVM tests now include `istanbul` in the parametrization.
=> Set istanbul as default EVM ruleset

CHANGELOG.md, brownie/network/contract.py, brownie/network/transaction.py, brownie/network/web3.py, brownie/project/main.py, docs/api-network.rst, docs/core-transactions.rst, tests/conftest.py, tests/network/contract/test_contract.py, tests/network/contract/test_contractcontainer.py, tests/network/contract/test_multiple_projects.py, tests/network/contract/test_unlinked_library.py, tests/network/transaction/test_new_contracts.py, tests/network/transaction/test_trace.py, tests/project/compiler/test_solidity.py, tests/project/ethpm/test_create_manifest.py
Detect contracts that are deployed via contract calls.
Closes #238 
1. Added `TransactionReceipt.new_contracts`, a list of addresses of deployments. This information is gathered during `TransactionReceipt._expand_trace`.
2. `ContractContainer.at` compares actual bytecode at an address against the expected bytecode. If there is a difference, it returns `Contract` instead of `ProjectContract`. This avoids various issues with traces and coverage evaluation when using Vyper's `create_forwarder_to`.
3. Fix minor pre-existing bugs related to failed contract deployments.
Run the tests. I included new test cases, this functionality is verified using `create_forwarder_to` in Vyper and `new` in Solidity (with both `CREATE` and `CREATE2`).
=> Deployments

CHANGELOG.md, brownie/network/transaction.py, docs/api-network.rst, docs/core-transactions.rst, tests/network/transaction/test_internal_transfer.py, tests/network/transaction/test_trace.py
Provide information on internal transfers during transactions.
Closes: #342
1. Add a `TransactionReceipt.internal_transfers` member that makes use of `@trace_property`
2. Scan the trace for `CALL` and `CREATE` opcodes with an non-zero value and record as dictionaries of `{'from', 'to', 'value'}` within `internal_transfers`.
3. Minor bugfix around transfers to fallback functions.
Run the tests.
=> Internal transfers

docs/api-test.rst, docs/api.rst, docs/conf.py, docs/core-accounts.rst, docs/ethpm.rst, docs/interaction.rst, docs/quickstart.rst, docs/tests-hypothesis-property.rst, docs/tests-pytest-fixtures.rst, docs/tests-pytest-intro.rst, tests/project/compiler/test_main_compiler.py, tests/project/compiler/test_solidity.py
1. Add intersphinx to docs to allow pretty links to external documentation.
2. Fix a few formatting issues.
=> use intersphinx, various minor docs fixes and improvements

brownie/project/build.py
Fix a compilation bug when a `REVERT` or `INVALID` occurs outside of a function.
=> bugfix: REVERT outside of function when generating revert map

CHANGELOG.md, brownie/_cli/test.py, brownie/project/scripts.py, brownie/test/managers/runner.py, brownie/test/plugin.py, docs/api-convert.rst, docs/core-contracts.rst, docs/core-types.rst, docs/tests-hypothesis-property.rst, docs/tests-hypothesis-stateful.rst, tests/test/plugin/test_stateful_flag.py
1. Add `--stateful` flag when running tests, to only run or exclude tests using the `state_machine` fixture
2. Warn instead of raising when an import spec can't be found during test hashing
3. Link to `NFToken` in docs as a real-world example of stateful testing
Run tests. I added new cases.
=> Stateful test flag, docs, bugfix

CHANGELOG.md, brownie/_cli/__main__.py, brownie/network/transaction.py, brownie/project/compiler/__init__.py, docs/conf.py, setup.cfg, setup.py, tests/conftest.py, tests/network/transaction/test_revert_msg.py, tests/network/transaction/test_trace.py, tests/network/transaction/test_verbosity.py, tests/project/compiler/test_solidity.py, tests/project/compiler/test_vyper.py
1. Add checks for contract size exceeding [EIP170](https://github.com/ethereum/EIPs/issues/170) limit. At compile time a warning is raised, at deployment a more meaningful revert string is given.
2. Allow access to the unexpanded trace on deployment transactions.
3. Bump version to `1.6.3`
Run the tests.
=> Eip170 checks, v1.6.3

CHANGELOG.md, brownie/project/main.py, brownie/project/scripts.py, brownie/test/plugin.py, tests/test/plugin/test_session_fixtures.py
Allow import of  `ContractContainer` instances from main `brownie` package when running tests. This behavior is documented, but for some reason was never actually implemented :fearful: 
Move namespace black magic from `project.scripts.run` to class methods in `project.main.Project`
Run the tests.
=> pytest ContractContainer imports

.github/PULL_REQUEST_TEMPLATE.md, README.md, brownie/test/fixtures.py, brownie/test/stateful.py, docs/index.rst, docs/tests-hypothesis-stateful.rst
Add a spinner to show progress on stateful tests when running pytest. Initially the spinner is yellow, once the test fails and is being reduced it changes to red.
Closes #358
Taking further advantage of the meta-class magic of `_BrownieStateMachine`.
Run the tests.
=> Stateful test progress spinner

brownie/_cli/analyze.py, docs/tests-security-analysis.rst, requirements.txt, tests/cli/test_analyze.py, tests/cli/test_cli_main.py
1. Bump `pythx` version to 1.5.3
2. Update `brownie analyze` based on MythX updates
1. Remove deprecated username/password options
2. Require authentication
3. Change environment variable to `MYTHX_API_KEY` and cli flag to `--api-key`
Run the tests.
=> Mythx updates

CHANGELOG.md, brownie/_cli/analyze.py, docs/tests-security-analysis.rst, tests/cli/test_analyze.py
- update documentation on Brownie security analysis using MythX
- add more code comments for the MythX plugin
- add feature where groups are automatically created on project submission
=> Update MythX plugin docs, add automatic analysis group creation

brownie/convert/utils.py
If an argument is of type "tuple" it's encoded as the concatenation of
the types that are inside. We should do the same for list of tuples.
This fixes a bug where brownie crashes when trying to encode an argument
with a type "ComplexStruct[]" where ComplexStruct is a solidity struct
with a few fields.
Example Solidity code to reproduce the bug:
```
contract Foo {
struct Bar {
uint256 something;
address something_else;
}
function frobulate(Bar[] calldata bar_list) external {
// do something
}
}
```
Before that fix, Brownie will crash when encoding the call to frobulate.
=> Fix an encoding bug for list of tuples.

brownie/network/rpc.py
One caveat is: https://github.com/trufflesuite/ganache-cli/issues/722
So for it to work as of now, you need to use a different port than 8545. But if you do that it works perfectly.
=> Add support for passing the --fork option to ganache.

brownie/test/output.py
"brownie test --coverage" crashed because of that when I included a contract that was left untouched for now.
=> Fix a DivisionByZeroError in case there is no line covered in a contract

brownie/exceptions.py, brownie/network/rpc.py
Fix #374 
Remove base class for RPC errors.
Run tests.
=> fix: do not pass rpc object to RPCConnectionError

brownie/_cli/console.py
Always use the same file for console history, regardless of which project is open.
=> use single console history file

brownie/network/account.py, brownie/network/contract.py, docs/api-network.rst, tests/conftest.py, tests/main/test_config.py, tests/network/account/test_accounts.py, tests/network/contract/test_contractconstructor.py, tests/network/contract/test_contracttx.py, tests/network/contract/test_default_sender.py
Add `Accounts.default` as a way to declare a default account for deploying contracts - Closes #289 
Run updated tests.
=> Add default account setting to Accounts

requirements.txt
Bump `py-solc-ast` dependency version to fix an issue with recursion. Fixes #392.
=> fix: bump solcast version to fix recursion issue

.travis.yml, tests/project/packages/test_popular_packages.py
Separate the travis jobs. Now that we can run 7 jobs at once, it should be quicker this way. Also it means when doctest fails from an external link, it's a lot less time to re-run it.
=> build: split travis jobs

brownie/_cli/test.py, brownie/test/managers/runner.py, brownie/test/plugin.py, tests/test/plugin/test_output.py
1. Allow `-s` flag in `brownie test`
2. Add `PytestPrinter` class to improve readability of output when stdout capture is disabled.
Closes #389 
1. When stdout capture is disabled, verbose output is automatically enabled.
2. `PytestPrinter` replaces the builtin `print` method during test execution to:
a. add a newline before the first line
b. add a second test id prior to reporting the test result
The final output ends up looking something like this:
```
tests/test_transfer.py::test_transfer RUNNING
this is some text from a call to print
tests/test_transfer.py::test_transfer PASSED
```
Run tests.
=> Pytest stdout capturing

brownie/project/main.py
fix: also remove tests.json when encountering old build format
=> fix: also remove tests.json when encountering old build format

brownie/__init__.py, brownie/_cli/networks.py, brownie/data/default-config.yaml, brownie/data/network-config.yaml, brownie/network/contract.py, brownie/network/state.py, brownie/project/build.py, brownie/project/ethpm.py, brownie/utils/sql.py, docs/api-brownie.rst, docs/api-network.rst, docs/compile.rst, docs/config.rst, docs/core-contracts.rst, docs/deploy.rst, docs/network-management.rst, tests/conftest.py, tests/network/contract/test_contract.py, tests/network/contract/test_ens_contract.py, tests/network/transaction/test_trace.py, tox.ini
* Deprecate existing `Contract.__init__` functionality in favor of class methods:
* `from_abi`: create manually from an ABI
* `from_ethpm`: create from an ethpm manifest
* `from_explorer`: create by querying etherscan (!)
* Store persistent data for live networks in an sqlite database at `~/.brownie/deployments.db`
* Allow aliasing and restoring persistent data between sessions via `Contract.__init__`
=> Updates to persistence

brownie/test/managers/runner.py
* fix: colorful output on skipped tests without xdist
=> fix: colorful output on skipped tests without xdist

tests/network/contract/test_contract.py
Temporarily apply `skipif` to the failing test in `tests/network/contract/test_contract.py`. Once the solidity team fixes the windows release for `v0.5.16` ([solidity/8697](https://github.com/ethereum/solidity/issues/8697)) this commit should be reverted.
=> skip failing windows test

brownie/project/main.py
In the compiler, use the project root folder as `allow_paths` rather than `./contracts`. This allows interface imports without using the `interface_sources` kwarg. Re: conversation on Gitter, it also ensures a more expressive error message when an interface import will not work.
`interface_sources` was a solution added prior to the allowing path remappings. Now that it's possible to import from anywhere, `interface_sources` seems less useful and is a good candidate for removal in v2.0
Run tests.
=> Adjust compile path

brownie/_cli/init.py, brownie/project/main.py, tests/cli/test_cli_main.py
Prevent `brownie init` from working in a directory that is not empty.
Related: #425 
Check that a directory is empty prior to init. From the CLI, you can use the `--force` flag to override the check.
Run tests
=> fix: do not initialize new project within a non-empty directory

README.md
I just ran `brownie init` in my `~/src` directory thinking it would prompt for the name of the project and it ended up making the files where I ran the command. We should add a note that `init` should be run from inside the new project's directory.
I'm not sure the best way to word it though.
Added a small change to the readme
N/A
N/A
- [N/A] I have confirmed that my PR passes all linting checks
- [N/A] I have included test cases
- [N/A] I have updated the documentation
- [N/A] I have added an entry to the changelog
=> Add note about where to run `brownie init`

brownie/convert/normalize.py, brownie/network/event.py, requirements.txt
Add support for events that cannot be decoded. 
Fixes #430 
Mostly handled upstream in  [`eth_event`](https://github.com/iamdefinitelyahuman/eth-event). Anonymous and undecoded events are now given the name `"(unknown)"` and undecoded topics are included as items within the event data.
Run the tests.
=> Handle undecodable events

brownie/_config.py, brownie/data/network-config.yaml, brownie/network/contract.py, brownie/network/rpc.py, brownie/network/state.py, brownie/network/web3.py, docs/core-contracts.rst, docs/network-management.rst, tests/cli/test_cli_networks.py
Simplify use of forked development network. Closes #435
* add `mainnet-fork` as development network, forking from Infura
* allow use of production network ID in `fork` field when declaring development network
* allow `Contract.from_explorer` when connected to forked development network
* test and debug querying deployments for transaction traces on mainnet
* add documentation (probably should be improved on in the future)
Fork it.
=> Mainnet fork

brownie/project/main.py, tests/project/test_brownie_mix.py
Remove check for initializing a project inside a project. This is no longer a concern because of the change to how config files are handled in `v1.7.0`
cc @skyge, thanks for notifying me of this on gitter
=> fix: remove now-redundant check for project-inside-project

brownie/network/contract.py, setup.cfg
Fix an issue when making a call to a contract with no owner while evaluating coverage. Again.
=> fix: no-owner when making calls during coverage eval

brownie/_cli/accounts.py, brownie/network/account.py
Fix #440
Modify the function `_import` in the file `/brownie/_cli/accounts.py` and the function `load` in the file `/brownie/network/account.py`
Run test
=> Fix importing key file error.

docs/compile.rst, docs/package-manager.rst
* Update the path remappings example to specifically show how to handle an NPM style import of Open Zeppelin.
* Bump OZ references  to `v3.0.0`
=> docs: update path remapping documentation

brownie/_cli/console.py, brownie/_cli/test.py, brownie/test/managers/runner.py, brownie/test/plugin.py, docs/core-transactions.rst, docs/tests-pytest-intro.rst, tests/cli/test_console.py, tests/conftest.py, tests/test/plugin/test_interactive_console.py
Add the `--interactive` flag to open a console during testing.  Closes #443.
* Use the `pytest_exception_interact` plugin hook to enter a brownie `Console` on a failed test, if the `--interactive` flag is active.
* Add a variant of `_sitebuiltins.Quitter` to handle `quit` and `exit` commands without closing `stdin`.
* Tests and docs
Run tests.
=> Add interactive mode for unit testing

brownie/network/account.py, brownie/network/contract.py, brownie/network/rpc.py, docs/api-network.rst, docs/core-rpc.rst, docs/tests-pytest-intro.rst, tests/network/contract/test_contractcall.py, tests/network/rpc/conftest.py, tests/network/rpc/test_redo.py, tests/network/rpc/test_undo.py, tests/test/plugin/test_coverage.py
Add `rpc.undo` and `rpc.redo` methods. Closes #454 
* `Rpc._add_to_undo_buffer` keeps a record of each transaction, and takes a new snapshot each time a transaction is performed.
* `Rpc.undo` and `Rpc.redo` move through the undo buffer.
Run tests.
=> Rpc.undo and Rpc.redo

brownie/test/managers/runner.py, tests/test/plugin/test_output.py
Add missing args/kwargs to the pytest `print` replacement. FIxes an issue reported by @skyge on [Gitter](https://gitter.im/eth-brownie/community?at=5ea92a0331a6d25d7c991f7b).
Adjustments to the `PytestPrinter` class in `brownie/test/managers/runner.py`
=> fix: add missing API params for pytest print function

brownie/exceptions.py, brownie/network/contract.py, brownie/network/main.py, docs/api-brownie.rst, docs/api-network.rst, docs/conf.py, docs/core-contracts.rst, docs/core-types.rst
Warn instead of raising an exception when block height is > 0 in development network - Closes #453 
I also got distracted and added some intersphinx docs references for `web3py`
* add brownie `Warning` classes, implement them in existing warnings
* warn instead of raising on block height > 0
* add documentation
Run tests.
=> Do not raise on non-zero block height

brownie/network/contract.py, tests/network/contract/test_contract.py
=> Call `getabi` in `Contract.from_explorer` when `getsourcecode` fails

brownie/_cli/compile.py, brownie/_cli/console.py, brownie/_gui/root.py, brownie/network/contract.py, brownie/project/build.py, brownie/project/main.py, brownie/test/fixtures.py, brownie/test/managers/base.py, docs/api-network.rst, docs/build-folder.rst, docs/core-contracts.rst, docs/tests-pytest-fixtures.rst, setup.cfg, tests/network/contract/test_interface.py, tests/project/main/test_interfaces_solc.py, tests/project/main/test_interfaces_vyper.py, tests/test/plugin/test_session_fixtures.py
Add `InterfaceContainer` and `InterfaceConstructor` objects.
Closes #436 
* All files within `interfaces/` are compiled and a stripped-down build artifact is stored at `build/interfaces/`
* These artifacts are used to create `InterfaceConstructor` objects, which act as a wrapper over `Contract.from_abi` to allow easy access to project interfaces.
* `InterfaceConstructor` objects are added as members of `InterfaceContainer` which is available as `interfaces` in the console and as a pytest fixture
Run tests.
=> InterfaceContainer and InterfaceConstructor

brownie/_cli/console.py, brownie/network/account.py, brownie/network/state.py, brownie/network/transaction.py, docs/api-network.rst, tests/network/account/test_account_transfer.py
Allow contract deployment via `Account.transfer`
* In `Account.transfer`, change `to` and `amount` inputs to optional kwargs.
* Fix bugs in `TransactionReceipt` when a transaction deploys a contract without the use of a `Contract` object.
* Add docs and tests
Run the tests.
=> Allow deployment via `account.transfer`

brownie/_cli/networks.py, brownie/data/network-config.yaml, brownie/network/main.py, brownie/network/web3.py, docs/api-network.rst, docs/network-management.rst
Allow custom timeout value for networks.
* Add a `timeout` field for each network within `network-config.yaml` - if not present, the default value is 30 seconds
* Set the default timeout for `mainnet-fork` as 120 seconds.
Run tests.
=> Custom request timeout setting

CHANGELOG.md, brownie/network/account.py, docs/api-network.rst, tests/network/transaction/test_attributes.py
Exposed `silent` bool parameter to Account.transfer() which will pass it on to TransactionReceipt.
Setting silent = True will suppress any console output for the transaction.
Related issue: #467
Exposed the parameter and added all the necessary tests and docs.
Run `test_silent_mode` or in brownie console: `a[0].transfer(a[1], "1 ether", silent = True)` should produce no console output.
=> expose silent parameter to transfer

brownie/_cli/test.py, brownie/test/managers/base.py
Add `--disable-warnings` flag to `brownie test` - closes #471 
Added a `pytest_terminal_summary` hook point to remove all exceptions when the flag is active.
Try it!
=> feat: allow disabling warnings when using brownie test

brownie/project/compiler/solidity.py, brownie/project/main.py
Allow import statements within interfaces.  Fixes #473 
Prior to compiling, change the cwd to `interfaces/` and include the root path in `allow_paths` when calling the compiler.
Run tests.
=> fix: allow imports within interfaces

brownie/project/main.py
Allow leading underscore in the root path of a project. Fixes #477 
Run tests.
=> fix: allow leading underscore in project root path

brownie/test/managers/runner.py
When running pytest, understand non-string values in `print`.
Fixes an issue [reported on Gitter](https://gitter.im/eth-brownie/community?at=5eae2d9d5cd4fe50a3e74b8a).
=> fix: handle non-string values in pytest print

brownie/network/transaction.py
When no function name is available, only show the contract name instead of `contractName.None`
=> fix: function names on proxied contract calls

brownie/network/account.py, brownie/network/rpc.py
Handle issues with `rpc.undo` / `redo` when using non-instant confirmations with Ganache.
Instead of adding the tx's to the undo buffer immediately, they are handled via a thread which waits for the tx to confirm.
Run tests.
=> fix: rpc.undo/redo with non-instant confirmations

CHANGELOG.md, brownie/network/account.py, brownie/network/contract.py, docs/api-network.rst, docs/core-contracts.rst, tests/network/account/test_account_deploy.py, tests/network/account/test_account_transfer.py, tests/network/contract/test_contractcall.py, tests/network/contract/test_contracttx.py
-  changed transfer, deploy and transact functionality to expose the nonce parameter
-  minor clarification in error messages
-  added test cases for manual nonce
Related issue: #484
Added nonce as kwarg or dict element when creating a transaction. E.g.:
accounts[0].transfer(accounts[1], nonce=5)
tester.doNothing({"from": accounts[0], "nonce": 5})
run tests
=> Expose nonce parameter

brownie/network/contract.py, tests/network/contract/test_contract.py
When using OSX, do not attempt to compile `0.4.x` contracts that are pulled from etherscan if the compiler version is not already installed.
Closes #487
=> fix: do not install solc 0.4.x on OSX in Contract.from_explorer

brownie/test/output.py, docs/api-test.rst
When gets a gas report, it is better to sort them by gas amount from large to small.
Run test with argument `--gas`
=> Sorted by gas amount used.

brownie/network/contract.py, brownie/project/compiler/__init__.py, docs/api-network.rst, tests/network/contract/test_contract.py
Update `Contract.from_explorer` with new Etherscan API
Closes #489 
* Compile with EVM ruleset indicated by API
* When API provides an implementation address, use it (if no `as_proxy_for` address is given)
Run tests.
=> Feat etherscan api

setup.cfg
Add the `--full-trace` flag when running pytest. This way the `__tracebackhide__` variable is ignored, and debugging is so much easier.
=> chore: add --full-trace flag to pytest config

brownie/project/compiler/__init__.py, brownie/project/compiler/solidity.py, brownie/project/compiler/vyper.py, brownie/project/main.py, tests/project/compiler/test_solidity.py, tests/project/compiler/test_vyper.py
Allow use of packages and path remappings when compiling interfaces.
* Add the `project.compiler.get_abi` method. It uses the standard JSON input/output for compiling, similarly to how `project.compiler.compile_and_format` works.
* Mark the old `vyper.get_abi` and `solidity.get_abi` methods as deprecated.
Run tests.
=> Allow path remappings in interfaces

brownie/network/main.py
Do not reset when disconnecting from a development chain. Since removing the check preventing connection when the block height is non-zero (#461) this action makes less sense.
=> fix: do not reset local environment on disconnect

tests/conftest.py, tests/project/compiler/test_solidity.py, tests/project/test_brownie_mix.py
* bump solidity version in tests to `0.6.7`
* remove parametrized tests for brownie mixes
Mixes are now being tested via a weekly scheduled workflow. The `travis-mix` is still verified in the brownie test cases to make sure that the functionality for downloading mixes is working.
This is to address an issue with testing the new `aave-flashloan-mix` where the mix tests expect to use a forked mainnet.
=> Remove brownie-mix parametrized testing

brownie/network/transaction.py, docs/api-network.rst, tests/network/transaction/test_attributes.py
Expose the timestamp for a transaction as `TransactionReceipt.timestamp`
`timestamp` is a `@property` method that calls `web3.eth.getBlock` to obtain the timestamp.
=> TransactionReceipt.timestamp

brownie/network/contract.py, brownie/network/transaction.py, docs/api-network.rst, tests/network/contract/test_contract.py, tests/network/contract/test_overloaded_method.py
Allow calls to `OverloadedMethod` without specifying the function signature. Closes #348
When an overloaded method only has one function with a given number of arguments, do not require the signature to be explicitly declared.
Run tests. I added test cases.
=> Improvements to OverloadedMethod

brownie/network/account.py, docs/api-network.rst, tests/network/account/test_account.py
Add the `Account.gas_used` attribute
Closes #515 
`gas_used` is a `@property` method that sums the `gas_used` attribute for all transactions sent from the given account.
Run the tests. I added a new case.
=> Account.gas_used

brownie/test/fixtures.py, brownie/test/managers/master.py, brownie/test/managers/runner.py
* When testing, close all projects during `sessionfinish`
* Improve logic for fixture resorting
Run tests.
=> Pytest minor fixes

brownie/test/managers/runner.py
Ensure the correct traceback frame is used when adding locals and globals to the debugging console.
Search `call.excinfo.traceback` to find the last frame where `path` is equal to the active test's path.
Load the console on a failed test
=> Correct frame for locals/globals with debugging console

brownie/network/account.py, brownie/network/transaction.py
Add failing transactions to the undo buffer prior to raising.
Fixes a bug during coverage evaluation when an `eth_call` reverts.
Move the raising logic out of `TransactionReceipt.__init__` and into a private method that is called after appending to the undo buffer.
Run tests.
=> add failed tx's to undo buffer before raising

brownie/exceptions.py, brownie/test/__init__.py, brownie/test/managers/base.py
Raise a warning when directly importing hypothesis.
Closes #525 
When the brownie plugin loads, monkeypatch `hypothesis.given` with a thin wrapper that raises a warning.
Run tests.
=> Warn on direct import of `hypothesis.given`

brownie/exceptions.py, brownie/network/account.py, brownie/network/transaction.py
Ensure revert messages are consistent between reverting calls and transactions.
* Move the majority of the message formatting logic to `TransactionReceipt.__init__`.
* Ensure dev revert comments are included on failed calls.
Some of this code feels hacky, but I didn't want to make any changes that could be considered breaking to the API.  In the `v2.0.0` refactor, all of this code will have to be revisited.
Run tests.
=> Standardize revert exceptions between calls and transactions

brownie/test/__init__.py, brownie/test/strategies.py, docs/tests-hypothesis-property.rst, tests/test/strategies/test_contract_strategy.py
Add `contract_strategy` - a hypothesis strategy to draw from `ContractContainer` objects.
Similar to `address`, it uses a `DeferredStrategy` and checks for contracts in active projects when it's accessed.
Run tests.
=> contract_strategy

brownie/network/account.py, brownie/network/web3.py
Allow use of custom gas strategies via the web3 gas price API
* When determining gas price, use `web3.eth.generateGasPrice` if no value is given in the config.
* Set the default strategy to check `eth_gasPrice`
Run tests.
=> Use `web3.eth.generateGasPrice` for gas price

brownie/_cli/networks.py, brownie/exceptions.py, brownie/network/state.py
* Allow use of `timeout` when adding new networks via CLI - fixes #531 
* Add more expressive error when attempting to use `Contract.from_explorer` in a local environment
=> Minor fixes

CHANGELOG.md, brownie/network/web3.py
Fix to allow wss connections. 
Tested by connecting to infura using wss endpoint.
Related issue: #541
see PR
Replace host for the mainnet network in the `network-config.yaml` file with `host: wss://mainnet.infura.io/ws/v3/$WEB3_INFURA_PROJECT_ID`
=> fix: allow wss connections

CHANGELOG.md, brownie/test/output.py, docs/api-test.rst, docs/tests-pytest-intro.rst, tests/test/plugin/test_output.py
grouped by contract
sorted by average gas
padded for table-like view
```
Gas Profile:
BrownieTester <Contract>
├─ constructor   -  avg: 1099591  low: 1099591  high: 1099591
├─ sendEth       -  avg:   23017  low:   23017  high:   23017
└─ doNothing     -  avg:   21437  low:   21437  high:   21437
EVMTester <Contract>
├─ constructor   -  avg:  711445  low:  711445  high:  711445
└─ modulusByZero -  avg:   21658  low:   21658  high:   21658
```
Closes #536
String formatting
`python -m pytest tests/test/plugin/test_output.py::test_print_gas --target plugin -n 0 -s --no-cov`
=> Improved --gas report

brownie/_cli/console.py, brownie/test/managers/runner.py
* Fix a path issue preventing the interactive debugger from working on Windows systems
* Fix a `colorama` issue on Windows related to the interactive debugger
* Properly convert the path using `BrowniePytestPlugin._path`, so that the lookup in `node_map` doesn't produce a `KeyError`
* Load and init `colorama` within the init process of `Console` to ensure it properly has an effect
Load the interactive debugger on a Windows system.
=> Windows interactive debugging fixes

CHANGELOG.md, brownie/project/main.py
Fixed FileNotFoundError when moving a contract source file.
Closes #539
Delete artifacts where no matching source is found and recompile the artifact.
Move a contract to a different folder and compile the project, then check the new artifact.
=> fix: recompile moved contracts

brownie/network/account.py, brownie/network/contract.py, tests/network/account/test_account_deploy.py
Return a `TransactionReceipt` when a deployment succeeds but the contract does not exist (self destructed during deployment).
Closes #537
=> Return TransactionReceipt on selfdestructed deployment

brownie/network/web3.py
Apply `timeout` to all types of `web3` connections.
Run the tests.
=> fix: apply timeout to all web3 connection types

brownie/exceptions.py
Raise a `ValueError` when the output used to create a `VirtualMachineError` cannot be properly parsed.  This should fix issues with `KeyError` when Geth complains about e.g. a hardware wallet not being unlocked, or a lack of peers.
=> fix: KeyError when handling some RPC exceptions

brownie/network/account.py
Check `web3.eth.accounts` when accessing an account via `Accounts.at` - useful if a new account was added from e.g. a hardware wallet being unlocked.
Run tests.
=> fix: check web3.eth.accounts when calling Accounts.at

brownie/network/web3.py
Fix how `timeout` arg is provided to `IPCProvider`
Connect to a client via IPC.
=> fix: web3 ipc timeout

brownie/exceptions.py, brownie/test/managers/runner.py, tests/network/account/test_account_deploy.py, tests/network/account/test_account_transfer.py, tests/network/contract/test_contractcall.py, tests/network/contract/test_contracttx.py
* Improve handling of `VirtualMachineError` in `brownie.reverts`
* Raise `ValueError` when the returned RPC error does not contain a data field.
Run tests.
=> VirtualMachineError fixes

brownie/_cli/test.py, brownie/project/scripts.py, brownie/test/plugin.py
* Bugfix: script imports from the stdlib
* Add project path to `sys.path` prior to loading pytest
* Improve readability of exception when compilation fails while running pytest
Run tests.
=> Pytest fixes

CHANGELOG.md, brownie/network/transaction.py
1. Distinguish if we have a ganache or geth trace and save to tx._trace_origin
2. Shift ganache gas costs by one step
3. Reduce depth of geth traces by 1
4. Added tx._call_cost = overhead cost to initiate the transaction
Related issue: #561 
see PR
tx.trace
=> fix: ganache shift bug & geth depth

brownie/network/rpc.py
Caught `ZombieProcess` and `NoSuchProcess` exceptions that can be thrown during the process scan on OSX. 
Fixes #570
I tested this version of the code and it has indeed fixed the error I was seeing in #570.
=> catch ZombieProcess/NoSuchProcess during `rpc.attach`

CHANGELOG.md, brownie/network/contract.py, brownie/network/event.py, requirements.txt, tests/network/test_event.py
Store event ABI data and decode events on a per-deployment basis, to avoid issues when different contracts have events with the same signature but different indexed elements.
Fixes #511 
* In `network/events.py`, event ABIs for specific addresses are held in `_deployment_topics`. When decoding an event, if the originating address has an event ABI, it is used.  If not, the global event ABI (`_topics`) is used.
* When updating `_topics`, if an ABI already exists it is only replaced if the previous record had no indexed values and the new one _has_ indexed values. So far, every occurrence of this bug that has been reported has been a result of no indexing, when the existing record does use indexing. Upstream in `eth_event`, providing an indexed ABI will now decode an unindexed event log.
Run …
=> Improve event decoding

brownie/project/main.py
Add a hook to allow modification of sources prior to compiling.
This is a _very basic_ implementation as a proof of concept toward what will eventually be #230 in Brownie 2.0.
Closes #505
I have tested locally.  For now not including any test cases - this is an undocumented behavior, and not something I think we should be encouraging the use of in it's current form.
=> load_source hook point

brownie/_cli/compile.py, brownie/project/main.py, tests/cli/test_cli_main.py
Raise `BrownieEnvironmentWarning` when loading a project from outside the current working directory.
Closes #566
* The warning is only raised if `project.load` is not called with an explicit directory.
* Made sure that all cli loading happens without a directory given (only had to modify compile)
I didn't add any new tests - this is a pretty minor PR and it can't really break anything.
=> feat: warn when project being loaded is not in cwd

brownie/network/account.py, brownie/network/rpc.py, docs/api-network.rst, requirements.txt, setup.cfg, tests/network/account/test_accounts.py, tests/network/rpc/test_launch.py
Add support for seed phrases.
Closes #334 
* Add the `Accounts.from_mnemonic` method, that relies on `eth_account` to do the heavy lifting.
* Display a seed phrase when generating a new account via `Accounts.add`
* Fix a bug preventing proper passing of mnemonics between `network-config.yaml` and `ganache-cli`
I also updated the docstring format in `Accounts` so everything is consistent.
Run tests.  I added a few new cases.
=> Support for seed phrases

CHANGELOG.md, brownie/_cli/analyze.py, brownie/_cli/compile.py, brownie/_cli/test.py, brownie/_config.py, brownie/_gui/source.py, brownie/data/default-config.yaml, brownie/network/contract.py, brownie/project/main.py, brownie/project/scripts.py, brownie/test/managers/base.py, brownie/test/managers/master.py, brownie/test/managers/runner.py, docs/config.rst, docs/structure.rst, tests/cli/test_cli_main.py, tests/project/test_project_structure.py, tests/project/test_scripts.py
Add config settings to modify the directory structure of a project.
Closes #578
* Add a config section `project_structure` which defines the expected directories.
* In `_config`, add a function `_load_project_structure_config` that checks a folder for a config file, and if yes returns the custom structure. If none is found it returns the default values.  This is necessary because we check for the existence of a brownie project based on the directory structure - so the settings must be loaded _prior_ to actually loading the project, in order to see that there is a project to load.
* Modified references to absolute directory names with references to the config settings throughout the code base.
Run the tests. I added a couple of cases to confirm the basic functionality and have been using …
=> Configurable project structure

.github/workflows/main.yaml
Remove `fail_ci_if_error: true` from the github workflow, so failed uploads to codecov stop failing the build.
=> ci: don't fail build when coverage upload fails

CHANGELOG.md, brownie/_config.py, brownie/data/default-config.yaml, brownie/network/contract.py, brownie/network/main.py, brownie/network/rpc.py, brownie/project/main.py, docs/config.rst, docs/deploy.rst, tests/project/main/test_deployment_map.py
* Add a setting to save deployment artifacts in development networks
* Add a deployment map that keeps track of deployed contracts, sorted by time
closes #576
Save deployment artifacts for development networks at build/deployments/dev/
Maintain a deployment map (of all deployments) at build/depoyments/map.json in the form of
```
{
"chainid": { 
"contractName": [
"contract address 1", 
"contract address 2"
]
}
```
* Deploy a contract and check `build/deployments`
* I wrote tests for this PR
=> Setting to save development artifacts and store them in a map

brownie/_config.py, brownie/test/__init__.py
* Adjust how snapshotting and reverts are handled when using `@given` property-based testing.
* Disable `report_multiple_bugs` - closes #567 
Previously, a snapshot was taken at the beginning of each test run and reverted to at the end. This caused an issue where if a test failed, the revert didn't occur and so the previous run's state leaked into future runs as hypothesis shrinks the failing example.
I have adjusted the logic so that the snapshot is only taken prior to the first run, and prior to each subsequent run a revert occurs.  Handling these actions before any test logic ensures they always occur, and moving the revert to the beginning means that if a test fails, it's still possible to use `-I` to drop in with the correct failing state.
Finally, I disabled `report_multiple_bugs` …
=> Hypothesis fixes

brownie/project/main.py, tests/project/packages/test_install.py
* Allow installing packages with a non-standard contracts folder - closes #497 
* Allow installing packages that won't compile
* If the project has no `contracts` folder, but there is another folder that contains contract files, create a configuration file with a `project_structure` field to point at the other folder
* If a project cannot compile, raise a warning but do not prevent it from installing. Users can still import individual contracts even if Brownie cannot load the project as a whole.
Run tests.
=> Project installation fixes

CHANGELOG.md, brownie/network/account.py, brownie/network/contract.py, brownie/network/transaction.py, docs/api-network.rst, docs/deploy.rst, tests/network/transaction/test_confirmation.py, tests/network/transaction/test_required_confirmations.py
Add `required_confs` as an argument to transactions with a default value of 1 (same as current behaviour).
Setting `required_confs = n > 1` will wait for n blocks to be mined before the transaction receipt is processed.
If during the confirmation time the transaction is dropped (uncle block), the transaction will wait until it is picked up again and has the required amount of confirmations.
if `required_confs == 0` the transaction will immediately return a pending tx receipt and not wait for a confirmation.
Add `tx.wait(n)` to retroactively add required_confs and wait until they are confirmed.
TODO: Still needs more documentation
Closes #587
Added the argument to all deply, transfer and transact functions.
Refactored the confirmation logic
I added tests for this.
or try …
=> Feat tx required confs

brownie/network/contract.py, docs/api-network.rst, tests/network/contract/test_contractcall.py
Expose `block_identifier` when making contract calls
Closes #586 
Added the `block_identifier` kwarg where it made sense. This is the same syntax that `web3.py` uses.
The only non-trivial thing I encountered was the case where calls are always handled as transactions (when evaluating coverage, for example). In this case, if the kwarg is provided I've opted to forgo running it as a transaction - since we can't very effectively perform a tx against historic state.
Run tests. I added some new test cases.
=> Block identifier

brownie/network/web3.py
Raise a more expressive exception when a forked dev environment stops working from a lack of archival state.
Closes #573 
Middleware!!!
Run the tests.
=> More expressive exception on stale fork

CHANGELOG.md, brownie/network/account.py, brownie/network/contract.py, brownie/network/transaction.py, docs/api-network.rst, docs/core-accounts.rst, docs/core-contracts.rst, docs/core-transactions.rst, tests/network/transaction/test_required_confirmations.py
* Add multithreading lock to send transactions from an account
* Add support for pending nonces and set pending nonce as the default nonce to use
Closes #588 
If the last transaction from an account is still pending, the pending nonce is the nonce of this transaction plus 1
I added two tests.
=> Feat pending nonce

brownie/network/rpc.py
Check input types for `rpc.sleep` and `rpc.mine` with `isinstance` rather than `type`, to allow use of `Wei` or other subclasses.
=> fix: check arg types with isinstance instead of type

brownie/exceptions.py, brownie/network/account.py, brownie/network/alert.py, brownie/network/contract.py, brownie/network/event.py, brownie/network/rpc.py, brownie/network/state.py, brownie/network/transaction.py, brownie/network/web3.py, brownie/test/managers/runner.py, brownie/test/plugin.py, brownie/test/stateful.py, setup.cfg
Only apply [`__tracebackhide__`](https://docs.pytest.org/en/latest/example/simple.html#writing-well-integrated-assertion-helpers) when the brownie plugin is loaded.
Closes #580 
During Brownie's `pytest_configure` hook, iterate over `sys.modules` and add `__tracebackhide__` to all Brownie modules.
This way, when running internal Brownie tests we can see the full tracebak without having to use `--full-trace` and also view pytest internals.
Make a test fail and look at the traceback.
=> Dynamically apply __tracebackhide__

brownie/network/web3.py, requirements.txt, tests/network/test_web3.py
Add `geth_poa_middleware` when connecting to a POA network
Closes #583 
After connecting, call `web3.eth.getBlock('latest')` and catch `ExtraDataLengthError`. If this exception is raised, add the required middleware.
Run the tests. I added a test case to confirm connection to rinkeby works.
=> Add POA middleware

brownie/network/rpc.py, tests/network/rpc/test_redo.py, tests/network/rpc/test_undo.py
Ensure `rpc.undo` and `rpc.redo` revert to immediately before a transaction is made.
Update the current snapshot after calls to `rpc.sleep` or `rpc.mine`.
Run tests. I added some new cases.
=> Rpc.undo/redo fix

brownie/test/strategies.py, docs/tests-hypothesis-property.rst, tests/test/strategies/test_address.py
Add a `length` kwarg to the `address` strategy.
Run tests.
=> Address strategy length

CHANGELOG.md, brownie/network/alert.py
Fix repeated alerts
Used `type` instead of `instanceof`, because `bool` is a subclass of `int` in python. 
It's a small change. Also automated tests should pickup if this is broken. 
- [✅] I have added an entry to the changelog
=> Fix repeated alerts by using type instead of instanceof

brownie/test/managers/base.py
Fix a formatting issue with verbose output from `hypothesis`.
Apply a check for ANSI-escape codes within the custom hypothesis reporter.  This was already happening during the hypothesis report generation - I just forgot to implement it here as well.
Run hypothesis tests with `-s` flag, make something fail.
=> fix: highlighting for hypothesis reporter

brownie/network/contract.py
When coverage evaluation is active, return the actual result of `eth_call`, rather than `tx.return_value`
This fixes an edge case where if `rpc.sleep` was called after the last transaction, and the call relies on `block.timestamp`, the act of performing a transaction can alter the result.
Run tests.
=> fix: return actual call during call-as-tx

brownie/_cli/test.py, tests/cli/test_cli_main.py
Fix a bug where `brownie test` always exitted with a zero status, even when tests failed :astonished: 
Catch the return code from `pytest.main` and exit with it.
failing - https://github.com/iamdefinitelyahuman/token-mix/runs/747035738?check_suite_focus=true
passing - https://github.com/iamdefinitelyahuman/token-mix/runs/747061341?check_suite_focus=true
=> pytest exit status

brownie/network/contract.py
Delete `required_confs` prior to making a call. This fixes an issue when making calls  with Parity (and i'm confused why Geth doesn't raise on this, frankly).
Run tests. Connect to kovan and see that you can make a call.
=> delete `required_confs` prior to making a call

brownie/_cli/run.py, brownie/test/managers/base.py, brownie/test/managers/master.py, brownie/test/managers/runner.py, brownie/test/output.py, tests/test/plugin/test_output.py
Adjust how coverage and gas reports are handled in `pytest`.
This fixes an issue where windows systems don't properly display the ANSI escape sequences, and generally improves the formatting of the output.
Run the tests.
=> Pytest reports

brownie/network/account.py, brownie/network/web3.py, brownie/project/ethpm.py, brownie/project/main.py, tests/network/contract/test_contract.py
* use `pytest.warns` to handle expected warnings within the test suite
* update deprecated API references to `eth_account` and `websockets`
Check that the CI shows no warnings.
=> Fix warnings

brownie/data/default-config.yaml, brownie/exceptions.py, brownie/test/managers/base.py, brownie/test/output.py, docs/config.rst, docs/tests-pytest-intro.rst, tests/test/test_report_output.py
Allow filtering of report data based on source path or contract name.
Closes #195 
Add a `reports` section to the config. See the updates to the documentation in the diff for an explanation of how it works.
Run tests. I added some new test cases to verify the behavior.
=> Filter reports by source path or contract name

brownie/test/managers/runner.py
Filter fixtures from namespace when using `--interactive` flag with pytest.
When building namespace from globals, do not include objects that have a `_pytestfixturefunction` member.
Debug something interactively.
=> Filter fixtures from namespace during interactive debugging

brownie/network/contract.py, tests/network/contract/test_contract.py
Add support for compiler JSON outputs when query source code from Etherscan.
Closes #494 
Run tests.  I updated a test that queries a source using JSON for source verification.
=> Fix etherscan json

brownie/_cli/run.py
When using the `-I` flag with `brownie run`, ensure the local namespace uses the correct frame.
Reverse `inspect.trace` when finding the correct frame.
Try it in the CLI
=> Enter correct frame with run --interactive

brownie/network/contract.py
Properly handle reverted `eth_call` output from older Geth versions.
Prior to decoding, check it the returned value begins with `0x08c379a0` (indicating an error string) or is empty.
=> fix: handle failed calls from geth

CHANGELOG.md, brownie/network/account.py, brownie/network/rpc.py, docs/account-management.rst, docs/api-network.rst, docs/config.rst, docs/network-management.rst, tests/project/test_brownie_config.py
Added the `unlock` setting to the network config in development networks.
This will pass the unlocked accounts to `ganache-cli` and add them to the `accounts` object.
Closes #618
Added `unlock` field to the config file, accepts a single address or multiple addresses
When `Accounts._reset()` is called, add the unlocked accounts to the end of the list.
I adjusted the tests
=> Feat unlock

brownie/_cli/__main__.py, tests/cli/test_cli_main.py
Exit with non-zero status when an exception is raised.
Fixes #635 
Use `sys.exit` to print the exception message in `brownie/_cli/__main__.py` - this results in an exit code of `1`.
Do something wrong.
=> fix: exit with non-zero status on exception

CHANGELOG.md, brownie/_cli/__main__.py, brownie/_cli/analyze.py, brownie/_config.py, brownie/network/contract.py, brownie/project/main.py, setup.cfg
Added a custom user agent to send with requests.
`{"User-Agent": f"Brownie/{__version__} (Python/{python_version})"}`
Example: `Brownie/1.9.3 (Python/3.6.8 final)"`
Related issue: #642 
Updated all `requests.get`  statements to include the user agent header.
Try and load a contract on Kovan.
=> Fix requests header

brownie/network/account.py
When determining the nonce for a new tx, confirm that the value returned by `eth_getTransactionCount` has changed from that of the last broadcasted tx by the same account.
This address this issue outlined in https://github.com/trufflesuite/ganache-core/issues/587
Launch the console using `--network mainnet-fork` and run a loop to deploy a contract.  Observe that nothing breaks :)
=> Check that nonce has properly incremented

.github/workflows/main.yaml, brownie/project/compiler/solidity.py, tests/conftest.py, tox.ini
* adjust the heuristic for non-payable function reverts to handle changes to `sourceMap` introduced in solc `0.6.9`
* adjust test parametrization to make it easier to run the tests against specific compiler versions
* add a new CI job that always runs against the latest version of solc
Verify that CI passes.
=> evm tests / fixed heuristic 

.pre-commit-config.yaml, CHANGELOG.md
my system has python3.8 instead of 3.7
Simple config change
I have the hooks installed and I was able to create this commit.
=> less restrictive default_language_version

CHANGELOG.md, brownie/data/default-config.yaml, brownie/data/network-config.yaml
Updated default gas to match what mainnet is at.
I'm not sure what people with existing installs should do. I'm guessing deleting `~/.browie/network-config.yaml` would work.
=> Update default gas limit to 12 million

brownie/network/contract.py, brownie/test/managers/runner.py
When using `brownie.reverts` to catch a dev revert comment, perform all calls as transactions. This fixes an issue where sometimes it is impossible to assign a revert comment to a failed call.
Run tests.
=> Run calls as transactions when catching dev revert comment

brownie/project/compiler/vyper.py, requirements.txt
* Reduce the length of the traceback on a failed vyper compile.  Fixes #658 
Catch `VyperException` and re-raise without a traceback
Run tests
=> Reduce vyper traceback

brownie/network/rpc.py
When running a script using `development` network, even using a `ganache` instance I launch, after finishing the execution the evm changes are reverted.
As pointed out by @iamdefinitelyahuman I removed the lines where invoked when exiting.
I haven't tried myself to automatically test the `atexit` hook, I can try to do so if required (I'm not a python dev so it might take me a while but a quick googling told me that hook is only executed then the process ends, in this case, pytest) . Manual test is required I'm afraid.
=> fix: avoids development network to revert when `atexit` is being called

brownie/data/default-config.yaml, brownie/network/account.py, docs/config.rst
Add "max" as an allowable setting for `gas_limit` in config.
Fixes an issue related to #650, where a development network can be launched with a lower block gas limit than specified in the config for transactions.
Run tests.
=> fix: add "max" gas limit setting

brownie/network/transaction.py
Always return the __last__ error string raised, if multiple error message occur when a complex transaction reverts.
Reverse the order of the trace prior to iterating to find `REVERT` or `INVALID` instructions.
Run tests.
=> Iterate over revert instructions in reverse

brownie/network/account.py, brownie/network/transaction.py
* only add `TransactionReceipt` objects to `history` when they are broadcasted from within brownie - closes #654 
* make `TransactionReceipt`'s `silent` kwarg `False` by default
* handle hexadecimal numeric values in traces (nethermind)
Run tests.
=> TransactionReceipt fixes

brownie/_cli/test.py, brownie/_config.py, brownie/data/default-config.yaml, brownie/test/plugin.py, docs/config.rst, requirements.txt
* Expose `hypothesis` phase settings
* add a `--failfast` flag to `brownie test` that causes `hypothesis` tests to fail sooner. This flag is automatically enabled when using `--interactive` mode
* bump hypothesis dep version
Closes #629 
Run tests.
=> Hypothesis settings

brownie/_cli/console.py, brownie/utils/color.py
Apply syntax highlights to Vyper exceptions.
Move `pygments` logic from `_cli/console.py` to `utils/color.py` - this is also a first step toward #407
Try to compile a vyper contract that contains an error.
=> Syntax highlighting for Vyper exceptions

brownie/network/contract.py
Before downloading an implementation contract, check that it's address is `!=` the address of the proxy contract.
Fixes #669 
In the console:
```python
>>> Contract.from_explorer('0x080bf510FCbF18b91105470639e9561022937712')
```
=> Fix infinite loop when downloading implementation contract

brownie/project/main.py
When downloading a brownie mix, check that the return status is 200 before streaming the download.
Fixes #671
=> Check for status == 200 before streaming brownie mixes

brownie/network/contract.py, brownie/network/transaction.py
Raise a meaningful error when a call to `debug_traceTransaction` fails.  Fixes #636.
* Remove `__slots__` and `__getattr__` logic from `TransactionReceipt`.  This was unnecessarily complex and the root of the issue.
* When an exception is raised while querying the trace, save it as `_trace_exc` and re-raise any time a trace attribute is accessed.
Run tests.
=> Meaningful error on failed trace

brownie/project/compiler/solidity.py
During compilation, extend `pcMap` if solidity does not provide a long enough `sourceMap`.
I'm still investigating the cause, but I've managed to produce the following minimal example that produces a `sourceMap` that is 7 instructions too short: https://gist.github.com/iamdefinitelyahuman/a6c658acb7e83371ecf730ebf6f8814d
Run tests.
=> Handle incomplete solc source map

brownie/_cli/test.py, brownie/convert/normalize.py, brownie/test/plugin.py
* add `--showinternal` flag to see internal traceback when running `brownie test`
* raise some exceptions from `None` to reduce traceback length
=> Minor traceback fixes / improvements

brownie/_cli/run.py, brownie/network/transaction.py
Add `--silent` flag to suppress transaction output when using `brownie run`.
Closes #621
=> Add `--silent` flag for brownie run

brownie/network/event.py, brownie/network/transaction.py, docs/api-network.rst, docs/core-transactions.rst, requirements.txt, tests/network/test_event.py
Add an `address` member to decoded event logs.
Closes #670 
Most of the work happened upstream in https://github.com/iamdefinitelyahuman/eth-event/pull/13. In brownie, the address is exposed as a member of `_EventItem`.
Run tests.
=> Add address to EventItem

brownie/_cli/console.py, brownie/network/account.py, brownie/network/transaction.py
* during multiline input, pressing tab at the start of a new line creates 4 spaces instead of opening the completion hints
* give correct hints for multiline input
* show completion hints for dict keys
Related issue: #558
Parse the input buffer using `tokenizer`.
Use the console!
=> Improvements to console auto-completion

brownie/convert/datatypes.py
When a value cannot be converted to an address, display the original value instead of `0x[value]`.
Preserve the original value during the attempted conversion and include it in the exception, rather than the half-converted value.
Run tests.
=> Convert to address error message

brownie/_cli/console.py
When the active text in the console ends with trailing whitespace, reset the completion hints.
Related to #683
Try it in the console!
=> Reset completion hints when active text has trailing whitespace

brownie/test/fixtures.py
Fix a bug in the `chain` fixture, it was returning `rpc` instead of `chain` :fearful:
=> fix: chain fixture

brownie/network/transaction.py, brownie/test/managers/runner.py
Fix a bug when expanding a trace where the contract is known, but the called function is not valid.
This was introduced in #679 - an attempt to decode the calldata for the unknown function raises an `AttributeError`.
During `_expand_trace`, check for `"function"` instead of `"contract"`
Run tests.
=> Bugfix: expanding trace with invalid internal function call

brownie/_cli/console.py
Check validity of open bracket when finding type hints / completions.
* For `(` check that the object has a `__call__` method
* For `[` check that the object has a `__getitem__` method
Try it in the console.
=> check for getitem/call before showing open paren hints

brownie/test/fixtures.py
When running stateful tests, don't show the spinner if stdout is not being suppressed  (the `-s` flag is active).
Don't add `capman` to the state machine if `capture == no`
=> Don't use stateful spinner when not suppressing stdout

brownie/network/transaction.py
Fix an issue when decoding an internal revert string.
Related to #679 
Ignore the first 4 bytes when decoding a revert string while expanding the trace.
=> fix: decoding internal revert msg

brownie/_config.py
Do not allow mutation of hypothesis settings.
Fixes #701 
In `brownie._config`, copy `settings` prior to mutation.
=> fix: copy hypothesis settings prior to mutation

brownie/network/account.py, brownie/network/contract.py, brownie/network/rpc.py, brownie/network/state.py
Minor improvements to console output:
* add a newline before showing RPC launch info
* only show contents of `ContractContainer` and `Accounts` in the console (makes pytest exception output easier to read)
=> Console output

brownie/network/contract.py, tests/network/contract/test_contract.py
* when handling a call-as-tx, do not call `chain.undo` if a transaction did not occur
=> Fix undo call as tx

brownie/project/compiler/solidity.py, brownie/project/sources.py, requirements.txt, tests/project/test_sources.py
Correctly handle structs and enums that are declared outside of a contract.
Closes #712 
* Fix the issue upstream in https://github.com/iamdefinitelyahuman/py-solc-ast/pull/12
* When compiling, ignore dependencies that are not contracts.
* Expand regex logic for finding contracts, to also handle structs and enums
Run the tests.  I expanded an existing case to look at this functionality.
=> Handle global structs and enums

CHANGELOG.md, brownie/test/plugin.py, tests/test/plugin/test_conftest.py
Fixes: #719
Load the project config during the discovery phase of conftest.py files
Everything should still work, and loading contract types in conftest.py should be possible
=> Load project before conftest

brownie/_cli/run.py, brownie/project/scripts.py, tests/cli/test_cli_main.py, tests/project/test_scripts.py
Allow use of `brownie run` outside of a project.
* Remove the requirement for a loaded project in `brownie._cli.run`
* Modify the import logic when loading scripts. The root folder is temporarily added to `sys.path` to ensure a script may be imported from anywhere.
Try it out.
=> Allow `brownie run` outside of a project

brownie/network/transaction.py
Fix an issue with coverage when using temporary projects.
Fixes #717
In `network.transaction`, check that a contract comes from a `Project` (and not `TempProject`) before considering it for coverage.
=> fix: ignore `TempProject` contracts when calculating coverage

brownie/_cli/__main__.py, brownie/_cli/console.py, brownie/_cli/run.py, brownie/project/scripts.py
* reduce length of path output when running scripts
* always enter console when using `brownie run -I` (even when script does not raise)
* correctly show container `__repr__` when loading console from `brownie run` or `brownie test`
=> Minor tweaks to `brownie run`

brownie/network/contract.py, brownie/project/compiler/solidity.py, requirements.txt, tests/conftest.py, tests/network/contract/test_contract.py, tests/project/compiler/test_solidity.py
Update to use `solcx` v1.0.0
A few API changes, nothing too major.  This could be done much more effectively to take advantage of the new API, but I think that's more in the scope of brownie v2
Run tests.
=> Use solcx v1.0.0

brownie/project/sources.py, tests/project/test_sources.py
Lessen the namespace collision restrictions.
Closes #729 
When looking for collisions, allow multiple uses of the same name so long as only one of the objects is a contract. This way projects using interfaces with the same name as the actual contract will now compile.
Try to compile https://github.com/compound-finance/compound-protocol using Brownie
=> Allow namespace collision between interfaces

.github/workflows/main.yaml
* Cache `vyper` installations in the CI
* Update to use `v2` actions where available
This should speed up the CI a bit and help with the windows tests that are failing when vyper fails to download.
=> CI caching

brownie/network/transaction.py
Fix an issue when formatting the expanded call trace.
Only use black on tuples and lists.
=> fix: formatting in call trace

brownie/network/transaction.py
Various fixes involving subcalls and call traces for transactions.
* correctly handle subcalls with no inputs
* catch `TypeError` during reverted trace (when source code not available / bytecode not matching)
* ensure `_expand_trace` never executes twice for the same tx
* display raw return data when it cannot be decoded
=> Transaction trace fixes

brownie/network/state.py, docs/api-network.rst
Add a block iterator to allow simple loops looking at the latest block.
`chain.new_blocks()` returns an iterator that polls `eth_getBlock` and yields new blocks as they arrive. You can set a buffer to get `latest-n` blocks and avoid chain reorgs, and a polling interval to avoid over-frequent requests.
This is a naive implementation and should be replaced with `eth_subscribe` at some point in the future.
=> Block iterator

brownie/network/transaction.py
Fix a bug when expanding a trace where the contract being called is not known (or incorrectly known).
Instead of only checking for the existence of a pcMap, handle a `KeyError` or `TypeError` when attempting to access it.
=> fix: expand_trace with unknown contract

brownie/exceptions.py
Ensure that when calling `__str__` on `VirtualMachineError`, the result is always a string.
=> fix: ensure VirtualMachineError properly returns string

brownie/network/contract.py, brownie/project/compiler/__init__.py
* Add a `selectors` attribute to `InterfaceConstructor`.
* Fix a formatting bug when compiling vyper interfaces to ABIs
=> Interface selectors

brownie/network/contract.py
Check that solc version is `>=0.4.22` when fetching from Etherscan.  Fixes a bug introduced when updating to use solc v1
=> fix: check min version when using from_explorer

brownie/project/build.py, brownie/project/compiler/__init__.py, brownie/project/main.py, brownie/project/sources.py, tests/project/main/test_recompile.py, tests/project/test_sources.py
* Fix a lingering issue caused by removing the namespace restriction between interfaces and contracts.
=> fix: issues with interface/contract namespace collision

brownie/network/event.py, tests/network/contract/test_contract.py
Warning instead of raising when an event is undecodable from incorrect number of topics.
Fixes https://github.com/iearn-finance/yearn-protocol/issues/7
=> feat: warn instead of raising on incorrectly formatted event

brownie/network/account.py, docs/api-network.rst
Add `gas_limit` as a kwarg in `Account.estimate_gas`
This fixes a bug when attempting to replace an underpriced transaction.
=> Add `gas_limit` to `Account.estimate_gas`

brownie/project/main.py
Correctly handle compiler checks in `compile_source` when either solc or vyper are not installed.
=> fix: handle no installed compiler when using `compile_source`

brownie/test/plugin.py
Do not capture `stdout` when loading a project at the start of `brownie test`.  This way, if the project must be compiled, the user sees relevant output.
=> fix: disable stdout capture when compiling project at start of tests

brownie/exceptions.py, brownie/network/account.py
When a contract fails to deploy because the bytecode is too large, give a more meaningful error message.
=> Improved error message for EIP170

brownie/network/account.py, brownie/network/contract.py
Use `evm_unlockUnkownAccount` to unlock arbitrary accounts.
This implements #758, but as it requires a beta version of ganache I am leaving the issue open for now. Once the feature moves from beta to stable I will bump the recommended version, add tests and documentation, and consider the issue closed.
Any address may be given as a string in the `from` field of a transaction dict.  Strings are converted to `Account` objects using `Accounts.at`.  If the address is unknown, it is unlocked with `evm_unlockUnkownAccount`.  Calling this endpoint prior to ganache `v6.11.0` appears to do nothing - and importantly, does not raise an exception.
Try it out!
=> Use evm_unlockUnknownAccount to unlock arbitrary accounts

brownie/network/contract.py
Check for `implementation()` method to determine proxy implementation. If this is not found, the previous method (trust etherscan) is used.
=> Attempt to determine implementation address without etherscan

CHANGELOG.md, brownie/_config.py, setup.cfg, setup.py
* update changelog
* bump version to `v1.11.6`
=> release: update changelog, bump version to v1.11.6

brownie/project/compiler/vyper.py, tests/network/transaction/test_revert_msg.py
Fix the heuristic for nonpayable contracts in Vyper >=0.2.5
Fixes #781
=> fix: nonpayable heuristic for vyper 0.2.5

tests/cli/test_cli_ethpm.py, tests/project/ethpm/test_get_manifest.py, tests/project/packages/test_install.py
Mark failing ethpm tests to be skipped.  This is a temporary measure - the functionality needs to be updated per the v3 spec.
=> Skip ethpm tests

brownie/_cli/console.py, brownie/network/contract.py
* Generate hints from actual objects when referencing an iterable index
* Show autosuggest for `Contract.function.call` or `Contract.function.transact`
* Add `Contract.function.estimate_gas` method
=> Console hinting improvements

brownie/test/managers/runner.py
Fix an issue causing failing tests to be displayed without coloring when skipped.
=> fix: colors for skipped tests that failed

brownie/test/managers/runner.py
Automatically add `tx` as a local variable when dropping into the console to debug a failing test.
=> feat: auto-add `tx` as a variable for interactive debugging

brownie/network/account.py, tests/network/account/test_account_transfer.py
Do not apply the gas buffer when sending ether to an EOA.
If gas_limit == 21000, don't use the buffer.
Run the tests,
=> Do not apply gas buffer to transactions where the receiver is an EOA

brownie/network/contract.py
Allow the use of `Contract` objects in the `from` field of a transaction.
Check for a `Contract` when building the tx, and if yes, use `Contract.address`
=> feat: allow sending tx's from a contract

brownie/network/state.py, docs/api-network.rst, docs/core-chain.rst, tests/network/state/test_txhistory.py
Add a `filter` method to the `TxHistory` object.
`TxHistory.filter` returns a filtered list of transactions. Each kwarg value must match against an attribute in the `TransactionReceipt`. A lambda can also be provided via `key`.
Run the tests. I added some test cases.
=> TxHistory.filter

brownie/test/output.py
Filter non-project contracts (dependencies such as OZ) out of the gas profile.
=> Filter non-project contracts out of gas profile

brownie/project/compiler/vyper.py, brownie/project/sources.py
Ensure that the entire source code is not displayed during the revert message on an attempt to pay a Vyper >=0.2.5 nonpayable contract
A bit of hackiness.
=> Fix: source offset for nonpayable revert in Vyper >=0.2.5

docs/ethpm.rst
Noticed that I couldn't create a manifest due to the organization of the keys in the example
=> Incorrect location of key for yaml

brownie/project/compiler/vyper.py
Expect `requests.ConnectionError` when querying vyper versions, instead of the builtin `ConnectionError`
=> target correct ConnectionError when pulling vyper versions

brownie/network/transaction.py
Prior to applying `black` when formatting a call trace, swap out `0x` for `b""` to avoid parsing error.
=> Replace `0x` with empty bytes prior to parsing with black

brownie/test/managers/runner.py
When running tests, do not connect to the network until immediately before running tests.
* Moved `network.connect` from `pytest_collection_modifyitems` to `pytest_collection_finish`.  The hook for `pytest_collection_finish` is handled as a hookwrapper so that the connection is guaranteed to happen after any user-defined plugins using the same hook point.
* Prior to connecting, check if there is already an existing connection.  This allows 3rd party plugins to handle connecting, if they desire.
Run some tests!
=> Connect to network immediatly prior to running tests

brownie/_cli/console.py
More tweaking of console autocomplete.
This fixes an issue preventing hints on `Contract.deploy(`
=> Console completions for attributes on containers

brownie/test/managers/runner.py
When locating the appropriate call frame prior to dropping into the console during testing, handle paths given as strings.
Fixes an issue reported by @michwill
=> fix: handle str when looking at traceback paths

brownie/project/main.py
Normalize project names when calling `brownie bake`
Closes #827 
Lowercase the given name.
=> Set bake project names to lowercase

brownie/__init__.py
Add `ZERO_ADDRESS` to the main brownie namespace:
```python
>>> from brownie import ZERO_ADDRESS
>>> ZERO_ADDRESS
"0x0000000000000000000000000000000000000000"
```
=> add ZERO_ADDRESS constant to main namespace

brownie/test/managers/runner.py
Fix an unhandled exception when attempting to use `--interactive` and a test contains a syntax error.
If a test cannot be collected, it is not added to `node_map` within the runner.  This results in a `KeyError` when trying to access the value to filter the local namespace.
To fix it, I've added a check that the path is present in `node_map` prior to opening the console. 
Try to interactively debug a test with a syntax error.  It still won't be possible, but you'll receive the correct exception.
=> fix: unknown test when attempting to enter console

brownie/network/contract.py
Allow the use of `ProjectContract` objects in the `from` field when sending a transaction.
In `brownie.network.contracts`, when determining the from address, check for an instance of `_DeployedContractBase` instead of `Contract`.
=> Allow arbitrary tx's from ProjectContract objects

brownie/__init__.py
Add an `ETH_ADDRESS` constant to the main namespace:
```python
>>> from brownie import ETH_ADDRESS
>>> ETH_ADDRESS
'0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE'
```
=> feat: ETH_ADDRESS constant

brownie/network/state.py, docs/api-network.rst, tests/network/state/test_blocks.py
Allow mining blocks at a specific height with `chain.mine`.
If multiple blocks are mined, they will be mined at equal intervals starting from `chain.time` and ending at `timestamp`.
=> Add `timestamp` kwarg to `chain.mine`

brownie/network/contract.py
Resolve the address when calling `Contract.at` to allow ENS links or non-checksummed addresses.
=> fix: resolve address during contract.at

brownie/network/transaction.py
Return raw hex when a revert message cannot be decoded within a transaction subcall.
=> fix: handle undecodable revert message in subcalls

brownie/network/account.py, brownie/network/event.py, brownie/network/state.py, brownie/network/transaction.py, docs/api-network.rst, docs/core-accounts.rst, docs/core-chain.rst, tests/network/transaction/test_confirmation.py
Add the `TransactionReceipt.replace` method for replacing pending transactions.
Closes #726
The logic flow for creating a `TransactionReceipt` had to be modified slightly. Creating the object is now optionally-blocking via the `is_blocking` kwarg (this had to be done to avoid making a breaking change). When broadcasting, the object is initially created via a non-blocking call, then added to `history`, then if `required_confs` is non-zero it calls `wait` to block until the necessary confirmations. By using this approach, each tx object is added to history immediately, so that users can `CTRL-C` and still access the pending the tx.
Replacement happens via `TransactionReceipt.replace` which accepts either an `increment` modifier or `gas_price` absolute and returns a new tx object.
As soon as …
=> Allow replacing pending transactions

brownie/network/transaction.py, tests/network/state/test_get_transaction.py
Fix two issues when attempting to create `TransactionReceipt` objects for externally broadcasted tx's:
* `EthAddress` object has no nonce, so querying the nonce is now handled via `web3.eth.getTransactionCount`
* even when a transaction request is non-blocking, wait for the transaction receipt if the transaction shows as already confirmed. This fixes an issue where `chain.get_transaction` was always returning tx's marked as pending (that were then marked as confirmed half a second later).
Run tests.  I added some cases to query txid objects from the mainnet that were failing prior to this PR.
=> Fix: TransactionReceipt for externally broadcasted tx's

brownie/network/transaction.py, brownie/network/web3.py, docs/api-network.rst, tests/network/test_web3.py, tests/network/transaction/test_trace.py
Do not attempt to query a trace when the node client does not support it.
1. Added the `web3.supports_traces` property method. This method calls `debug_traceTransaction` without any arguments and checks the returned error code.  If the return code is -32601, the endpoint does not exist. Any other error means the endpoint does exist.
2. Within various `TransactionReceipt` methods, check for `web3.supports_traces` prior to attempting to query a trace. If `False`, give a more meaningful error than the standard "RPC endpoint does not exist / is not available".
3. Fix an issue where reverting transactions would raise if a trace is not available, because of an attempt to access the revert reason.
Run the tests. I've added some new cases.
=> Improved handling of trace queries / exceptions

brownie/network/account.py, brownie/network/contract.py, docs/api-network.rst, docs/core-contracts.rst, tests/network/account/test_account_transfer.py
Allow broadcasting reverting transactions in a live environment
Closes #765 
* Added the `allow_revert` position arg to `Account.deploy` and `Account.transfer`
* Expanded the exception messages when a tx fails to broadcast due to a failed `eth_estimateGas` call or because `allow_revert == False`.
* Run the tests.
* Attempt to make a reverting tx on the mainnet
=> Allow broadcasting reverting transactions in a live environment

brownie/network/contract.py
Prevent assignment on `Contract` objects that would replace an existing contract method.
Closes #537 
Implement custom `__setattr__` logic that only takes effect after the `__init__` method runs.  See the diff - it's fairly straightforward.
Run tests.
=> Disallow assignment over contract functions

brownie/project/sources.py
Fix an issue where projects installed via `brownie pm` that included interfaces, could not compile.
Closes #845 
In `Sources.get`, check for known interfaces prior to attempting a general-purpose load from the filesystem .
```
brownie pm install Macarse/GenericKeep3rV2@0.0.1
```
=> Fix: interfaces in installed projects

brownie/test/managers/base.py, brownie/test/managers/runner.py, docs/tests-pytest-fixtures.rst, docs/tests-pytest-intro.rst, tests/test/plugin/test_markers.py
Add the `require_network` pytest marker to allow only running a test when a specific network is active.
Closes #810 
* Add the marker via `pytest_configure`
* Implement the logic within `pytest_runtest_setup`
* Add documentation - I've created a new section for markers, expect more in another PR soon:tm:
* update tests
Run tests.
=> Add `require_network` marker

brownie/network/transaction.py, brownie/test/fixtures.py, brownie/test/managers/base.py, brownie/test/managers/runner.py, docs/api-test.rst, docs/tests-coverage.rst, docs/tests-pytest-fixtures.rst, tests/test/plugin/test_coverage.py, tests/test/plugin/test_skip_coverage.py
Convert `skip_coverage` and `no_call_coverage` to markers, deprecate them as fixtures.
The marker logic is how handled via `pytest_runtest_call` or `pytest_runtest_setup`.  Using the fixtures raises a deprecation warning.
Run the tests.  I've updated some existing cases.
=> Convert `skip_coverage` and `no_call_coverage` to markers

brownie/exceptions.py, brownie/network/account.py, brownie/network/gas/bases.py, brownie/network/gas/strategies.py, brownie/network/main.py, brownie/network/state.py, brownie/network/transaction.py, docs/api-network.rst, docs/core-accounts.rst, docs/core-gas.rst, docs/toctree.rst, tests/network/test_gas.py, tests/project/compiler/test_solidity.py
Automatic repricing of transactions.
Closes #727 
When setting `gas_price`, you may now use an object that subclasses from `GasABC`:
* `SimpleGasStrategy` for simple strategies that are called once
* `BlockGasStrategy` which is called every `n` blocks
* `TimeGasStrategy` which is called every `n` seconds
For strategies that trigger tx replacement, returning a non-`None` value broadcasts a new transaction.
Thus far I have created two actual strategies, based around the [gasnow](https://www.gasnow.org/) API.
Try it out!
=> Automatic transaction repricing / replacement

brownie/network/transaction.py, docs/api-network.rst, docs/tests-pytest-intro.rst, tests/network/transaction/test_revert_msg.py
Expose the dev revert string, even when there is an actual revert message.
Related issue: #806
Added the `TransactionReceipt.dev_revert_msg` attribute.
Run the tests. I expanded / updated related tests.
=> Add `TransactionReceipt.dev_revert_msg`

brownie/exceptions.py, brownie/network/transaction.py, brownie/test/managers/runner.py, docs/api-test.rst, tests/network/transaction/test_revert_msg.py, tests/test/plugin/test_reverts.py
Allow specific targeting of dev revert string within `brownie.reverts`
Closes #806 
```python
with brownie.reverts(dev_revert_msg="dev: foo"):
...
```
Also fixed a bug that I missed in #805 causing the dev revert string to not always be queried when requested.
Run tests.  I added a few new cases.
=> Target dev revert reason in `brownie.reverts`

brownie/test/managers/runner.py, docs/api-test.rst, tests/test/test_revert_context_manager.py, tox.ini
Allow use of regex matching in `brownie.reverts` context manager (continuation of #862)
Closes #807 
Added two new kwargs, `revert_pattern` and `dev_revert_pattern`, for matching error strings and dev revert strings.
Run the tests.  I've added some new tests to cover this.
=> Allow regex in `brownie.reverts`

brownie/network/contract.py
Improve the error message when attempting to make a contract call without giving a `"from"` field, and where the contract has no default owner.
Closes #851
=> Improved error message for ownerless contracts

brownie/network/transaction.py
When pulling data from the memory within a trace, append zero-bytes when the available memory ends prior to the expected length.
Fixes an issue found as reported by @banteg and found in https://github.com/banteg/cornichon/pull/1
=> fix: add zero-bytes when memory ends too soon

brownie/project/build.py, brownie/project/compiler/__init__.py, brownie/project/compiler/solidity.py, brownie/project/compiler/utils.py, brownie/project/main.py, tests/project/main/test_interfaces_solc.py
Include compiler artifacts for dependencies within `build/contracts/`
Closes #772
=> Include depdendency artifacts in `build/contracts/`

brownie/network/contract.py, docs/api-network.rst
Add `ContractContainer.decode_input` for decoding arbitrary calldata into a contract.
=> `ContractContainer.decode_input`

brownie/network/account.py
Ensure `to` field is correctly checksummed prior to calling `eth_estimateGas`
=> fix: convert `to` to address prior to gas estimation

CHANGELOG.md, brownie/network/contract.py, tests/network/contract/test_contract.py
Added support for [EIP-1822](https://eips.ethereum.org/EIPS/eip-1822) proxy pattern detection to `Contract.from_explorer`.
=> Detect EIP1822 proxy

CHANGELOG.md, brownie/_cli/bake.py
fixed a typo
```
$ curl -s -o /dev/null -w "%{http_code}" https://github.com/brownie-mixes
404
$ curl -s -o /dev/null -w "%{http_code}" https://github.com/brownie-mix
200
```
=> fix: correct link to mixes

brownie/project/compiler/solidity.py
Handle missing source nodes due to yul optimizations
Closes #890 
Check for the existence of `contract_id` within the source nodes prior to accessing the dict. If it does not exist, handle the instruction as though it's unmapped.
=> Handle missing source nodes due to yul optimizations

tests/network/contract/test_contract.py
Update implementation address for failing test
Closes #899 
Confirm CI is passing (except `evm-latest` which is still expected to fail).
=> Update implementation address for failing test

brownie/network/transaction.py, brownie/project/compiler/solidity.py, tests/network/transaction/test_revert_msg.py
Add support for the new solidity [error codes](docs.soliditylang.org/en/v0.8.0/control-structures.html#panic-via-assert-and-error-via-require)
Related issue: #897 
The tests should be _mostly_ passing now. There's still one more issue to address before we can consider 0.8.0 fully supported.
=> Solidity error codes

brownie/network/transaction.py, brownie/project/compiler/solidity.py
Fix tracebacks and dev revert reasons for solc 0.8.0 when optimization is enabled.
Closes #897
Solidity 0.8.0 introduces a new optimization where all reverts/requires that include an error string are handled by the same bytecode. The source mapping for this bytecode points at the first revert statement that the compiler encounters - as such, when attempting to generate a traceback, all reverting tx's that include an error string will appear to fail at the same location.
To fix this, I'm flagging that first revert as the "optimizer revert". When it's encountered, I step back through the trace until I find a jumpdest (arriving at the optimizer revert from a yul optimization), and then further until i find an instruction with a source offset. This offset is the actual location of the failing …
=> Fix for tracebacks and dev reverts in solc 0.8.0

brownie/network/transaction.py, brownie/utils/color.py, brownie/utils/output.py
Improved formatting and more information about events in `tx.info()`
* refactored `brownie.utils.output.build_tree` so it can be used for the events
* events are now shown with a tree in order to display which contract the event fired from
* highlighting is now handled via `pygments`
Try it!
=> Improved event information for `TransactionReceipt.info`

CHANGELOG.md, brownie/_cli/networks.py, brownie/_config.py, brownie/network/rpc.py, docs/config.rst, docs/network-management.rst, tests/project/test_brownie_config.py
Exposed `--chainId` -> `chain_id`  and `--networkId` -> `network_id` parameters for ganache-cli to the brownie network config.
Forked networks will default to the `chain_id` of the origin network (can be overwritten).
**IMPORTANT:** `--chainId` requires ganache-cli version 6.11.0 or higher. To use this feature, ganache-cli has to be updated.
Related issue: #901
Added the parameters to the list of accepted network settings.
Fetch `chain_id` from origin network and set as default when a fork (and no custom `chain_id`) is specified.
Accepted types for both values are integers (ganache will ignore anything else). Other types will issue a warning.
Run updated tests.
=> Feat chainid networkid

brownie/network/account.py, brownie/network/gas/bases.py, brownie/network/state.py, brownie/network/transaction.py
Fix an issue with console output when using a gas strategy.
Closes #884 
Track the `silent` status of the original transaction and ensure each subsequent transaction has the same setting.  See the code comments for a more detailed explanation.
Replace some transactions!
=> Fix: console output when auto-replacing transactions

brownie/network/transaction.py
Handle malformed calldata when decoding subcalls in a transaction trace.
See diff.
=> Handle malformed calldata in subcalls

brownie/project/main.py
Previously, `brownie bake` would assume the master branch was in each
brownie-mix repository. Now it checks the github api to verify the
default branch first.
Resolves eth-brownie/brownie#915
- Modified `MIXES_URL` to now require 2 arguments when formatting the string, the project_name and default_branch
- Created a function `_get_mix_default_branch(mix_name: str) -> str`, which given the brownie-mix name, returns the default branch for the repository
- Modified `from_brownie_mix` function to call `_get_mix_default_branch`, and include the returned value when formatting `MIXES_URL`
Related issue: #915 
I checked [stackoverflow](https://stackoverflow.com/questions/16500461/how-do-i-find-the-default-branch-for-a-repository-using-the-github-v3-api) for how to find the default branch of a …
=> fix: make bake cmd use default brownie-mix branch

brownie/network/event.py
* use `ReturnValue` instead of `List` for some return types related to events.
* Allow direct comparison of a sequence with an `_EventItem`. The comparison assumes a check against the values within the event, in the same order as they're given in the ABI.
Run tests.
=> Event return types and comparisons

brownie/network/transaction.py
Decode reverting transaction events only upon request.
This prevents other trace-related operations from being blocked when an event cannot be decoded.
Move the call from `_decode_trace` into the `events` property method.
Run tests.
=> Lazily decode events from the trace

brownie/network/transaction.py
Allow transaction replacement for tx's broadcast outside of brownie.
In `TransactionReceipt.replace`, if the sender is not an `Account` object, check if an `Account` exists and if yes - use it!
Try it.
=> Replace transactions broadcast outside of brownie

brownie/_cli/console.py
When loading the console without an active project, ensure the cwd is within `sys.path`.
=> fix: add cwd to path when console is opened without an active project

CHANGELOG.md, brownie/network/account.py, brownie/network/contract.py, brownie/project/build.py, brownie/project/compiler/__init__.py, brownie/project/compiler/solidity.py, brownie/project/main.py, brownie/utils/toposort.py, docs/api-network.rst, docs/deploy.rst, requirements.txt, tests/network/contract/conftest.py, tests/network/contract/test_contract.py, tests/network/contract/test_verification.py, tests/project/compiler/test_solidity.py, tests/project/main/test_interfaces_solc.py
Added a method to publish source to etherscan for solidity contracts.
`DeployedContract.publish_source()`
Related issue: #411 
Flatten source code into one file (thanks Ben for starting on this). Make sure to include all comments, proper licensing and exactly one pragma statement. 
Will wait for contract to be recognized by etherscan after deploying, then submit request for verification and finally wait for the verification to be processed and report the result.
`deployed = MyContract.deploy({'from': account}, publish_source=True)`
and also 
`MyContract.get_verification_info()`
-> https://ropsten.etherscan.io/address/0x6De9c6197bB8f61177C30946d90CAC2720272c5c#code
Tests are adapted for the changes to the solc versioning, but no new tests for this feature are written yet.
=> Feat publish source

brownie/network/event.py, brownie/network/transaction.py
Lazily decode events even for confirmed transactions.  This avoids the warning for an incorrectly structured event, except when the user explicitly asks to look at the events.
The `@property` decorator is my friend.
Run the tests.
=> Lazy event decoding

brownie/project/compiler/solidity.py
=> fix: check that instruction is PUSH before popping pushed bytes

brownie/network/contract.py
magic
Related issue: Fixes #945
Printed `implementation_eip1967` and `implementation_eip1822` and saw:
```
implementation_eip1967: b''
implementation_eip1822: b''
```
No idea why they are empty now 🤷 
Run `weth = Contract("0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2")`
Make sure you are running with a clean `~/.brownie` folder.
=> fix: issue 945

brownie/project/compiler/solidity.py
There is an issue when processing instructions which are not `PUSH` that will lead to bad `int` conversion.
Related issue: #873 also related to PR #935 
The issue is almost identical to above but occurs in another location.
=> Fix non-push instructions

CHANGELOG.md, requirements.txt
Bumped eth-event version in requirements.txt to 1.2.1 to mitigate the topic generation bug for events with dynamic/fixed size tuple inputs.
Resolves #955
Related iamdefinitelyahuman/eth-event#15
Just changed the 1.2.0 -> 1.2.1 :)
Since this changes a dependency I ran the `pytest` suite just to verify stuff doesn't break.
=> fix: bump eth-event minimum version to 1.2.1

docs/api-network.rst, docs/compile.rst, docs/core-transactions.rst, docs/network-management.rst, docs/structure.rst, docs/tests-pytest-intro.rst
Updated some links that showed as broken in `tox` output.
Manually
Click 'em
=> Fix some broken links

brownie/project/main.py
Allow `project.load` to load projects from installed package.
For example:
```python
from brownie import project
curve_dao = project.load('curvefi/curve-dao-contracts@1.1.0')
```
=> Load installed packages as projects

brownie/_cli/networks.py
Add a diagnostic message when users pass `brownie networks list verbose=true` to nudge them towards passing `brownie networks list True`.
=> wip: Add diagnostic output when reading networks list verbosity fails

CHANGELOG.md, README.md, brownie/network/rpc.py
I've extended the check that is determining if a RPC client is already running to also query the network connections in addition to  the process list. The error I've observed on a `Ubuntu 18.04 LTS` was that only localhost RPC clients could be detected with the existing code. Even dockerized RPC clients bound to the `127.0.0.1` could not be attached.
I've adapted the logic to first try the process list and then the network connections.
I've also implemented hostname resolution which becomes handy when the RPC client is bound to a specific hostname instead of IP which is often the case when used in docker-compose environments.
```bash
docker run -p 8545:8545 trufflesuite/ganache-cli
```
Then in another terminal
```bash
brownie console
```
=> Support for dockerized RPC clients + Hostname resolution when attaching to RPC clients

brownie/_cli/console.py, brownie/data/default-config.yaml, docs/config.rst
- pass down prompt_toolkit EMACS or VI
Added a new option to console section to be able to choose editing mode.
Simple patch of Console class.
1. Change editing_mode in default configuration file from emacs to vi
2. Start brownie console and notice that vim keybindigs are available
- [-] I have included test cases
- [-] I have updated the documentation
- [-] I have added an entry to the changelog
=> feat: add option to choose console editing mode

CHANGELOG.md, brownie/network/event.py, brownie/network/transaction.py
Added support to decode different variants of `ds-note` events, commonly used across MakerDAO ecosystem.
Tested with:
- https://github.com/dapphub/ds-note/blob/master/src/note.sol
- https://github.com/makerdao/dss/blob/master/src/lib.sol
- https://github.com/makerdao/dss/blob/e2cdd97046d456b760c1223b5ffb86c540b9e096/src/vat.sol#L63
```python
network.connect('mainnet')
tx = chain.get_transaction('0x7d5799a3622477847731d22ddd8d38031a949159446a727b3e4e7542ad558806')
tx.info()
```
=> feat: decode ds-note events

brownie/_cli/console.py, brownie/test/managers/runner.py
Modify how the console is exited during pytest interactive debugging:
* `continue` runs the next test
* `exit()` or `quit()` halts execution
This might surprise some people who've gotten used to the current behavior but I'm guessing more will like it than dislike it.
Added a `exit_on_continue` kwarg to the init method of `Console`. When `True`, a check in `Console.runsource` checks the source before compiling, and if `continue` is found, it raises a `SystemExit` with error message `"continue"`. This error message is then caught in the pytest runner and used to decide how to interpret the exit command.
Try it.
=> Exit console via `continue` during pytest interactive debugging

brownie/test/plugin.py
Add a commandline flag `--brownie-project` to force loading a project outside of the current working directory when using the brownie pytest plugin.
Closes #994 
Within `test/plugin.py`, I've added the `_get_project_path` method to find the current project path.  Because the path required prior to `pytest_addoption`, it must be extracted directly from `sys.argv`.  It's a bit hacky but it solves the issue.
Try it.
=> Flag to run tests against project outside of current working directory

brownie/network/middlewares/__init__.py, brownie/network/middlewares/caching.py, brownie/network/middlewares/geth_poa.py, brownie/network/web3.py
* generalized logic for adding middlewares to the brownie `web3` object
* a basic implementation of for RPC-call caching
Middlewares are automagically loaded from all files within `brownie/network/middlewares`. The only requirement is that they subclass `BrownieMiddlewareABC`. They are automatically added upon connection and removed at disconnect.  The exact spec is fairly well documented within the natspec and comments.
The cache has two components:
* A short-term cache that lasts as long as the current block. This is useful because it means elsewhere in the code, there's no longer an onus to think about "am I hitting this endpoint too often?" - which gets exponentially more complex when you start using threading (such as with tx replacement). Related - #850
* A long-term cache that …
=> Middlewares and Caching

brownie/network/rpc/__init__.py, brownie/network/web3.py
Fix an issue when connecting to `ethnode` that I really should've caught yesterday.
* Add the `Web3.reset_middlewares` method, that uninstalls and readds all middlewares for the given `Web3` object.
* Standardize the sequence of post-init actions within `Rpc.launch` and `Rpc.attach` to ensure that middlewares are always correctly added __after__ the local client has finished loading.
=> reset_middlewares, standardize connection init sequence

brownie/network/middlewares/caching.py, tests/network/rpc/test_cache.py
Expand the logic when determining if bytecode may be cached. In particular, consider an indirect `SELFDESTRUCT` via `DELEGATECALL`.
Thanks to @banteg for pointing this one out.  I am a bad devloper and I'm not sure why any of you use my code.
The new implementation is fairly well commented, but the gist of it is:
* remove the bytecode after `PUSH` instructions to avoid false positives
* scan for `DELEGATECALL` and if it isn't preceded by `PUSH20 [address] GAS` assume it to be dynamic and thus not cacheable
* where an address is hardcoded, also check if the target address is cachable
This isn't perfect but it should err on the side of caution.
I actually wrote tests on this! Good job, me.
=> Expand `getCode` caching logic for SELFDESTRUCT via DELEGATECALL

CHANGELOG.md, brownie/network/rpc/__init__.py, tests/network/rpc/test_attach.py
I've fixed the bug where OSX clients would get a `psutil.AccessDenied` exception when connecting to a dockerized ganache without sudo.
Fixes #992 
I've added an extra check for the `platform.system()` to handle OSX clients a bit differently due to the open issue in psutils: https://github.com/giampaolo/psutil/issues/1219
Instead of querying all available network connections, I'm searching for the `com.docker.backend` process and attach to that. Added some tests for it as well.
On a mac run:
```bash
docker run -p 8545:8545 trufflesuite/ganache-cli
```
and then in another terminal:
```bash
brownie console
```
=> Fix for RPC-attaching to a dockerized ganache in OSX.

brownie/network/rpc/__init__.py, tests/network/state/test_blocks.py
Fix a bug in `chain.mine` that was introduced in `v1.14.0`, where if no timestamp was explicitly given all blocks were mined with a timestamp of `1`.
Correctly handle default args. Oopsie.
Run the tests.  I added some coverage for this case.
=> Issue with chain.time timestamp

brownie/network/middlewares/caching.py
Ensure the node client supports filters before adding the cache middleware.  Fixes #1008 
During `RequestCachingMiddleware.get_layer`, attempt to make and query a filter prior to returning a layer.
Try it using the `bsc-main` network where filters are disabled.  CZ, if you're reading this, give us filters!
=> Ensure node client supports filters before adding cache middleware

brownie/network/contract.py
Correctly handle `pragma abicoder v2` when verifying Solidity source code.
=> Support 'abicoder v2' in source verification

brownie/network/contract.py
Add support for `BSCSCAN_TOKEN` as an environment var, for verifying source code on bscscan.com
Fairly self explanatory - see code.
=> Support for BSCSCAN_TOKEN env var

brownie/data/default-config.yaml, brownie/network/state.py, brownie/network/transaction.py, brownie/test/output.py, docs/config.rst
* Add `reports.only_include_project` as a config setting, to disable filtering non-project contracts from gas report
* Add a new `avg (confirmed)` column to the gas report, for the average transaction cost only on tx's that did not revert
=> Improvements to gas reporting

brownie/network/contract.py
Fixed a regression introduced [here](https://github.com/eth-brownie/brownie/commit/ed7adacd008d2a633c47c701ccf905954fe66a40#diff-9d15ba572e3097f4a9461dc8fe0a0dfc6d7f6015e935930526ebfb4ba0fa0cefL781).
Reverted an erroneous refactor to its previous state.
Also added renaming `balance` Contract class member to `wei_balance` on name clash instead of rendering it inaccessible.
`Contract('0x5dbcF33D8c2E976c6b560249878e6F1491Bca25c').balance()` on mainnet should be non-zero.
=> fix: balance contract member override

brownie/_cli/console.py
Fixed an annoyance when firing up an interactive console in a project directory. It loads the project automatically, but it previously didn't inject contract and interfaces in a global namespace, which made the environment different from scripts or tests.
=> fix: add project to brownie namespace for console

brownie/data/network-config.yaml, tests/cli/test_cli_networks.py
Plz, merge https://github.com/eth-brownie/brownie/pull/961/files first
I did it based on that branch to avoid conflicts in the yml.
=> FTM integration

CHANGELOG.md, CONTRIBUTING.md, brownie/_config.py, brownie/_expansion.py, brownie/project/main.py, docs/config.rst, requirements.in, requirements.txt, tests/project/test_brownie_config.py, tests/test_expansion.py
This feature adds POSIX-style environment variable expansion to Brownie's config. You can now access environment variables, like you would `os.environ`, or, define them using the new top-level `dotenv` flag brownie's configuration. 
* Adds `dotenv:` key to `brownie-config.yml`
* Reads environment vars from both `os.environ` as well as a `.env` file (when specified)
* Supports default values, like so: `${THE_REAL_DEAL:-dentacoin}`, or `${NEEDS_MORE_COWBELL:-true}`
* Supports basic value inference for `int` and `bool`.
Related issue: #1000 
```sh
export SHOW_COLORS=true
```
`brownie-config.yml`
```yaml
console:
show_colows: ${SHOW_COLORS}
```
`.env`:
```ini
BUILD_DIR=/dev/teapot
```
`brownie-config.yml`
```yaml
dotenv: .env
project_structure:
build: ${BUILD_DIR}
networks:
default: …
```
=> feat: brownie config supports env vars

brownie/test/managers/runner.py
When opening a console during pytest interactive debugging, find the local frame based on the project path rather than the test path. This ensures the correct namespace when a test fails during logic imported from another file, such as an inherited class.
Tweaks to `pytest_exception_interact`
=> Find console frame based on project path

brownie/network/account.py
Pass the passphrase kwarg through
`accounts.from_mnemonic(...)`
=> add passphrase kwarg to from_mnemonic

CHANGELOG.md, brownie/project/main.py
Adjusted error messages when interacting with the Github API.
Related issue:  Fixes #1051 
Can try a failing auth request e.g. `brownie pm install org/some_private_repo@1.2.3`.
Pretty clear from inspection too
=> Apply auth error message to 404 responses too.

CHANGELOG.md, brownie/project/main.py, docs/package-manager.rst
Have `_stream_download()` also use `GITHUB_TOKEN`
Related issue: fixes #1054 
Move `GITHUB_TOKEN` retrieval into standalone helper function, pass headers as optional arguments to `_stream_download()` and `_get_mix_default_branch()`
Looks like this was also not being used in `from_brownie_mix()`.
Can try installing a github brownie package from a private repo (it now succeeds).
Not too clear how to easily/reasonably include this in the test cases - the test would probably have to rely on an external AUTH token and an active internet connection, or some swanky mocking.
=> Fix - Use GITHUB_TOKEN when downloading zipballs

brownie/network/account.py, brownie/network/web3.py
Include `chainId` when signing transactions to support [EIP-155](https://eips.ethereum.org/EIPS/eip-155) replay protection.
Closes #1021 
* Add a `chain_id` member to `Web3` that calls `eth_chainId` upon first access and caches the result for subsequent requests
* In `LocalAccount._transfer`, add `chainId` before signing the transaction
Run the test suite.
=> Include chainId in transactions (support EIP-155)

brownie/network/account.py
Fixed allow_revert error message syntax to be consistent with actual transaction parameter syntax.
=> Fixed allow_revert error message syntax

brownie/_cli/console.py
Fix a recursion error within the console when attempting to print the output of `globals()` or `locals()`.
Fixes #1014 
The bug was due to how console output is generated - under the hood, `globals()` is mutated to `__ret_value__ = globals()` and then `__ret_value__` is printed.  However, because the return value _contains_ `__ret_value__` we end up dying recursion death as we try to format dict-inside-dict-inside-dict.
The fix is simply to remove `__ret_value__` from locals prior to generating the console output.
Open the console and type `locals()` or `globals()`.
=> Remove `__ret_value__` prior to writing to console

brownie/network/transaction.py
Handle `StopIteration` in two places within `TransactionReceipt`.
Fixes an issue with a tx that fails due to out-of-gas, and another when trying to generate a traceback for a tx that failed in a contract where the source code is not verified.
Closes #969 
Add `try:except` around two iterators.
=> handle StopIteration within tx receipts

brownie/network/transaction.py
Gracefully handle a transaction where the target is a contract that has self destructed.
Fixes #1045 
`try:except` within `_set_from_tx`.   Traces and other aspects of the receipt may still raise, but this way at least the object can be generated without issue.
=> Handle missing contract when generating receipt

brownie/network/middlewares/caching.py
Avoid caching requests to create a new block filter.  This fixes an issue causing brownie to freeze when the RPC client normally allows filters, but drops them frequently due to network congestion (looking at you, Binance Smart Chain).
Add `eth_newBlockFilter` to the list of RPC endpoints that should never be cached.
Spend some time using BSC.
=> Do not cache `eth_newBlockFilter`

brownie/network/contract.py
I found a spot where we were still using ETHERSCAN_TOKEN instead of BSCSCAN_TOKEN.
```
$ export BSCSCAN_TOKEN=xxx
$ brownie --network bsc-main console
>>> Contract.from_explorer("0x2170ed0880ac9a755fd29b2688956bd959f933f8")
```
=> more BSCSCAN_TOKEN

brownie/network/account.py
Fix an issue where an incorrect nonce can be used when creating multiple tx's with gas strategies.
Instead of simply assuming the last tx within `history` is the highest nonce, actually sort by nonce to make sure the highest one is used.
=> fix: do not assume last nonce == highest nonce

brownie/network/account.py
* Allow use of kwarg for password in `Account.load`
* Check if an existing path is a directory before attempting to load a keystore file
These are both minor quality of life fixes based on some stuff I ran into while aping.
=> Minor `Account.load` updates

brownie/network/account.py, docs/account-management.rst, docs/api-network.rst
Add support for [`clef`](https://geth.ethereum.org/docs/clef/tutorial) as an account signer.  This makes it possible to use hardware wallets in Brownie.
* added the `ClefAccount` class to handle interactions with `clef`.
* `Accounts.connect_to_clef` and `Accounts.disconnect_from_clef` for connection/disconnection
* updated docs
Try it! I've tested manually a bunch.. not sure how to best write unit tests.
=> Support for clef as an account signer

brownie/network/alert.py
Fixed alert message bug
Closes #939 
Full disclosure: This change was made in-browser, so I haven't run tests locally. It's just a variable name change though, so I don't expect it to be controversial.
msg variable was reset, causing the bug: I created a new variable for printing the message
Create an alert with repeat != False, verify that the message updates accordingly
=> Fix alert message bug

brownie/network/gas/strategies.py
Allow use of `Wei` within gas strategies.
Fixes #1088
=> fix: use `Wei` in gas strategies

docs/tests-pytest-fixtures.rst
Fix typos in tests-pytest-fixtures.rst
Fixed typos.
NA
NA
- [NA] I have confirmed that my PR passes all linting checks
- [NA] I have included test cases
- [NA] I have updated the documentation
- [NA] I have added an entry to the changelog
=> docs: fix typos in tests-pytest-fixtures.rst

CHANGELOG.md, brownie/data/network-config.yaml, tests/cli/test_cli_networks.py
Add polygon networks to default network-config.yaml
Related issue: #934 
Fixes: #1111 
Nothing special, just looked up the polygonscan api url, and the infura polygon api url, added to the network-config file
drop into a console, fetch a contract, do some matic related stuff
=> feat: polygon network integration

docs/quickstart.rst
Fixess a small typo in the Quickstart section of the `docs`
Simply changed the text.
Navigate to `https://eth-brownie.readthedocs.io/en/stable/quickstart.html` to check the typo.
=> docs: fix typo in quickstart section

CHANGELOG.md, brownie/network/transaction.py, tests/network/transaction/test_subcalls.py
Minor patch of the logic in transactions.py to handle direct calls/staticcalls/delegatecalls to empty accounts. 
Fixes #1105 
Added to the if statement that determines whether a call is being made to a contract, and handled calls to the datacopy address from vyper.
There is a parameterized test verifying functionality in both solidity and vyper contracts.
=> Fix: Subcalls to empty accounts

CHANGELOG.md, brownie/network/account.py, docs/account-management.rst, requirements.in, requirements.txt, tests/network/account/test_accounts.py
This change adds a dependency for the `eip712` package and uses it to implement a new `LocalAccount.sign_message` method.
Related issue: https://github.com/ApeWorX/eip712/issues/4
Added the `eip712` dependency to `requirements.in`, used `pip-compile` to update `requirements.txt`, used that new package to implement the `LocalAccount.sign_message` method, wrote a new test that defines an `EIP712Message` and signs it using a local account with a private key loaded, verified the test result, ran lint & other pre-commit steps, added docs, added entry in the changelog.
I wrote a new test alongside the existing `LocalAccount` tests in `test_accounts.py`
```
$ pytest -k test_sign_message 
...
== 1 passed in 12.87s ==
```
=> feat: add support for EIP-712 message signing

brownie/_gui/report.py, brownie/_gui/root.py, brownie/_gui/source.py
Currently, the values of the report dropdowns in the brownie GUI are loaded once on startup and remain static afterwards. The values can be changed by the user, but neither the values nor the highlights are updated when another contract is selected - even if that contract has no corresponding report.
This can become inconvenient in different ways: 
- If someone is just starting to write tests or only running a specific subset of tests, when checking for coverage of branches or statements through the GUI, if no highlights are available for the selected contract it is not clear whether that is due to the absence of a report or to the tests failing to cover any part of the contract for that report type. 
- When switching between contracts, the report and report type dropdowns retain their …
=> Bind GUI report dropdowns to currently displayed contract

CHANGELOG.md, brownie/data/network-config.yaml, brownie/network/contract.py
- Add support for `POLYGONSCAN_TOKEN` 
-  Fix `id` of Polygon Mainnet to make `polygon-main-fork` work
Copied code of etherscan/bscscan. Not sure if this could be made more elegant
Launch `polygon-main-fork` network and fetch/call contracts.
=> Add support for `POLYGONSCAN_TOKEN` env var

brownie/test/managers/base.py
Add `no_call_coverage` as custom marker to fix a warning when running tests.
=> fix: add `no_call_coverage` as custom marker

CHANGELOG.md, brownie/network/transaction.py
Solidity now has typed errors. This keeps parsing them from crashing brownie.
We can figure  out actually parsing them in this PR or merge this and do that later.
Check for the string selector before trying to parse as a string
revert with the new typed errors.
=> don't crash on solidity 0.8.4 typed errors

CHANGELOG.md, brownie/project/compiler/__init__.py
Fixes #1137
Add support for mappings to subfolders
```yaml
compiler:
solc:
version: null
optimizer:
enabled: true
runs: 31337
remappings:
- "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
- "@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@3.4.0/contracts"
```
=> fix: support subpath in remappings

CHANGELOG.md, brownie/data/network-config.yaml, brownie/network/contract.py, docs/network-management.rst, tests/cli/test_cli_networks.py
Added Xdai to network config.
Enabled fetching ABI from blockscout api
Note: Although the blockscout api tries to be similar to etherscan, there are a few dis-similarities (mainly in naming conventions and return values)
Related issue: #934 
Handled the case when the explorer api is set to blockscout, easy to identify due to naming conventions and url
Drop into a brownie console and try fetching the source of a contract. here is one: [0x22Bd2A732b39dACe37AE7E8f50A186f3D9702e87](https://blockscout.com/xdai/mainnet/address/0x22Bd2A732b39dACe37AE7E8f50A186f3D9702e87)
=> feat: XDai support

brownie/project/compiler/vyper.py, tests/network/transaction/test_subcalls.py
Updatres to make brownie compatible with vyper 0.2.14.
The actual dependency bump will come in another PR soon :tm:
Some hacky bits during compilation to support the new optimized reverts.
Run the tests.
=> vyper 0.2.14

brownie/network/middlewares/caching.py
Fixes related to caching:
* do not cache `eth_sendTransaction` and `eth_sendRawTransaction` responses - when combined with tx replacement this can leave the main thread stuck on a loop forever, waiting for a lock to release. Maybe related - #1115 
* gracefully handle any exceptions raised when creating a filter _after the initial filter was created successfully_. In some cases (looking at you, BSC) public nodes allow a filter to be created and queried several times, then disable and rate limit that specific endpoint. Related - #1159 
Do stuff, see what breaks.
=> Fixes around caching

requirements-windows.txt, requirements.txt
Bump `py-solc-ast` to `v1.2.9` which fixes an AST issue for `solc >=0.8.3`.
This _might_ solve one of more of the following issues: #1127, #1114, #1087, #1076
=> bump `py-solc-ast`

CHANGELOG.md, brownie/network/account.py, docs/account-management.rst, tests/network/account/test_accounts.py
=> feat(account): Signing plain, defunct messages (for EIP-191) (refs: #1163)

brownie/_cli/console.py
Preserve the active input line when outputting to the console.
A custom printer object: `ConsolePrinter`.
Try it. I've been using it for a few weeks now without issue.
=> Preserve active input when writing to console

brownie/network/account.py, brownie/network/transaction.py
Adjust the flow of logic around making a new transaction to reduce the likelihood of a threadlock. Also improves the verbosity with a tx to show when things are still working (particularly when the tx was broadcast but has not yet shown in the mempool).
The main thing happening here is removing the use of web3.py's `wait_for_transaction_receipt` and applying similar logic directly in brownie.  This gives us some more control over how everything is handled and allows the improved verbosity.
For the locks, I reduced the amount of logic inside the lock to only broadcasting the actual transaction.
=> Modifications to tx flow

brownie/network/account.py, brownie/network/contract.py, brownie/network/state.py, brownie/network/transaction.py, requirements-windows.txt, requirements.in, requirements.txt
Add support for specifying EIP-1559 style transactions.
`transact` method not accepts `max_fee` and `priority_fee` arguments which are mutually exclusive with legacy `gas_price` argument. I went for shorter names instead of `max_fee_per_gas` and `max_priority_fee_per_gas` to keep Brownie users' sanity.
It also adds `chain.base_fee` to look up the base fee of the latest block. It it used when a user only specifies `priority_fee`, in which case `max_fee` is inferred as `base_fee * 2 + priority_fee`, which should be enough to get the transaction through within 6 blocks of raising base fee (actually 1.125⁶ is needed, explore if that would be a better constant here).
=> feat: eip1559 transactions support

brownie/network/account.py
Fix a bug introduced in #1179 related to the undo buffer - incorrect args were being passed which broke `chain.redo` and the failing test went unnoticed because I'm a pleb.
=> fix: support eip1559 in undo buffer

brownie/network/account.py, brownie/network/state.py, brownie/network/transaction.py, docs/api-network.rst, docs/core-chain.rst, docs/core-contracts.rst, docs/core-gas.rst
Added info on dynamic transactions to documentation.
Updated the example block in docs to show new fields introduced in London.
Added `chain.priority_fee` which suggests a max priority fee. Provisional, depends on https://github.com/ethereum/web3.py/pull/2100.
Fixed a bug with receipt trying to read nonexistent `gasPrice` field.
=> docs: eip1559 docs and fixes

brownie/network/rpc/hardhat.py
Modify hardhat config to support london ruleset.
Set `initialBaseFeePerGas` to 0 within the default config. This allows for a gas price of 0 when testing, so that hardhat can be used within existing test suites without breaking anything.
=> Modify hardhat config to support london ruleset

brownie/network/account.py
Filter `maxFeePerGas` and `maxPriorityFeePerGas` when making a call to check if an eip-1559 tx will revert. This is necessary to allow transactions where the max fee is set below the current base fee.
=> Fix: `eth_call` revert check with eip1559 tx's

brownie/network/rpc/hardhat.py
Modify a reference to `web3.py` to avoid the now-deprecated camelCase functions.
=> fix: getBlock -> get_block

CHANGELOG.md, brownie/data/network-config.yaml, brownie/network/rpc/__init__.py
Modified the RPC `kill()` function to recursively kill all child processes. This ensures that hardhat terminates properly on exit.
Also changed timeout of `hardhat-fork` to 120s to match other forknets.
Related issue: #1199
```
brownie console --network hardhat
quit()
brownie console --network hardhat
```
=> Recursively kill all RPC child processes on exit

CHANGELOG.md, brownie/network/transaction.py
Added a check in `_raise_if_reverted` to skip the dev_revert_string lookup if the contract is not found. This can happen if the contract is deployed via another contract (or somehow otherwise not logged in the deployment map).
I added an if statement.
Deploy a contract from inside a contract and check if it reverts. A test like this should pass:
```
with brownie.reverts():
contract.transactionWillRevert()
```
- [YES?] I have confirmed that my PR passes all linting checks
- [NO] I have included test cases
- [N/A] I have updated the documentation
- [YES] I have added an entry to the changelog
=> Handle contracts not found during revert check

CHANGELOG.md, brownie/test/output.py
The previous behavior expects all functions to have a report for both
statements and branches. If not, it removes the whole contract from the
coverage report.
While the assumption seems reasonable, some functions seem to only have
either one of statements or branches, ending up in removing contracts
that would otherwise contain useful coverage information.
This is related to #1087 and should at least be a partial fix to it
Avoid excluding the contract when one of the functions in the contract was missing coverage information 
Run the coverage report
=> fix: do not remove contract from coverage report if a function is missing statements or branches

brownie/project/compiler/solidity.py
When generating the `pcMap`, correctly handle branches occuring in a function outside of a contract.
Fixes #1198 
Check if the parent of the function node is a `SourceUnit` and if yes, do not include a contract name.
From inside the console:
```python
Contract.from_explorer('0xBA12222222228d8Ba445958a75a0704d566BF2C8')
```
=> fix: handle function outside contract

brownie/data/default-config.yaml, brownie/network/__init__.py, brownie/network/account.py, brownie/network/main.py, docs/api-network.rst, docs/config.rst, docs/core-gas.rst, docs/toctree.rst, requirements-windows.txt, requirements.txt
Allow setting default `max_fee` and `priority_fee` to simplify eip1559 transactions.
* Added the `network.max_fee` and `network.priority_fee` methods
* Added `max_fee` and `priority_fee` to the networks config
* Updated docs
Try it in hardhat.
=> Add `network.max_fee` and `network.priority_fee`

brownie/network/account.py
Remove `gasPrice` and `gas` from `ClefAccount` formatters, since it's already formatted before `_transact` are called.
Related issue: #1210 
Remove from the dict.
2 lines removal :)
=> Remove gasPrice, gas  from ClefAccount formatters

brownie/network/middlewares/hardhat.py
Reformat revert strings outputted from Hardhat to be compatible with that Brownie expects (based on Ganache output).
Fixes #1201 
Closes #1204
Modify the Hardhat middleware.
Run the example repo from #1201
=> Hardhat revert reasons

CHANGELOG.md, brownie/test/managers/base.py
Added a hotfix to prevent `brownie test -s` from crashing when skipping tests 
Related issue: Fixes #1215 
Added missing `report.longrepr` tuple. Ideally, it should contain the reason written in `@pytest.mark.skip(reason=...)`, but I couldn't figure out a way to do that with the existing flow
Add `@pytest.mark.skip()` or `@pytest.mark.require_network("dummy")` to a test and run `brownie test -s`
=> Prevent brownie from crashing when skipping tests with -s

docs/install.rst
I have added a small line in the doc if you are updating from an old version of brownie you won't have the hardhat network in the network-config.yaml
=> Add informations about missing hardhat network.

brownie/network/multicall.py, tests/network/test_mulitcall.py
Ended up testing 4 some different ways to handle this (some combinations as well).
- Lock enter/exit of context
- Lock pending calls access / bytecode swap
- Add dictionary with per-thread data (pending calls, block number)
- Add a separate thread for flushing
Easiest and quickest was just locking on enter/exit (we'd need to use a RLock to handle reentrancy within the same thread though, and then also handle more reentrancy issues (like maintaining a queue of block numbers). However, opting for locking on queue/bytecode access + per-thread dictionary was what I ended up going with. For now it gets the job done with the least amount of headache.
Will definitely need to revisit this along with reentrancy in the future.
=> fix: change lock acquire/release in multicall

brownie/data/network-config.yaml
Add `arbitrum-main` to the default network config.
Closes #1230 
Followed the instructions at https://arbitrum.io/bridge-tutorial/
Try it.
=> feat: add arbitrum to network config

docs/deploy.rst
=> Docs: typo: Etherem => Ethereum

brownie/network/transaction.py, docs/api-network.rst
When replacing an EIP1559 transaction, create another EIP1559 transaction.
* The max fee is modified according to the given modifier or new absolute value.
* The priority fee is always multiplied by 1.1, which seems to be the minimum required by Geth.
Try it.
=> Support EIP1559 in `TransactionReceipt.replace`

brownie/network/state.py, brownie/network/transaction.py
Related issue: closes #1241
I compared nethermind and erigon traces and realized that they return stack values differently.
Check traces against transactions in #1241.
=> Handle erigon traces and other failing transactions

brownie/project/main.py
Fixed #1168
I don't think adding a specific test case nor a changelog entry is needed for a such modification
Related issue: #1168
.env entry is present in generated .gitignore file after brownie init
=> GH-#1168: add .env to .gitignore after brownie init

brownie/network/state.py
Add an optional `only_confirmed` kwarg to `history.clear` to only remove transactions that have confirmed.
Self explanatory.
=> Allow only clearing confirmed tx's

brownie/project/compiler/__init__.py, brownie/project/main.py
Related issue: #1242 
by adding a `solc_version` parameter to `get_abi`
not necessarily a draft, but would like some feedback before moving on to including a test case, updating the docs and/or adding an entry to the changelog.
if none of that is needed for a small fix such as this one, i guess it can directly be merged :)
=> pass solc version to get_abi from compiler config file

docs/quickstart.rst
Change the wrong argument passed to `Token` constructor in the example in `quickstart.rst`.
Change `1e20` to `1e21` in the quickstart doc.
According to the example below, `_totalSupply` should be `1e21` so that `t.balanceOf(accounts[1]) == 1000000000000000000000`. Please let me know if there is anything wrong.
=> docs/quickstart.rst: fix wrong arg in constructor

.gitignore, brownie/exceptions.py, brownie/project/main.py
This change would allow numerics to be included in project names.
=> Auto generated project name includes numerics

docs/tests-hypothesis-property.rst
Adds a missing `import` in a test example.
- [Y] I have confirmed that my PR passes all linting checks
- [N/A] I have included test cases
- [Y] I have updated the documentation
- [N/A ] I have added an entry to the changelog
=> Add missing import in test

brownie/project/flattener.py, tests/network/contract/test_verification.py
Fix regex to support paths with your single quotes along with double quotes when building verification info.
Fixes: #1322
Add a capture group for the quote used, and a backreference to the group for the closing quotes.
Tests should still pass, (updated one to include single quotes in the import path).
=> fix: match against double/single quote paths

brownie/network/contract.py
Fix contract verification for contracts with linked libraries (as opposed to embedded libraries).
Fixes: #1317 
Add all libraries w/ there deployment addresses to the dictionary of compiler settings
Check #1317 can be compiled with solc using the standard json input from `get_verification_info()`
=> fix: add libraries for linkage with solc in verification info

brownie/project/sources.py
Result of `re.findall()` was not previously checked before use, which resulted in runtime exceptions for one of my contracts (compilable with solc).
=> Check if re.findall actually matches

CHANGELOG.md, brownie/project/compiler/__init__.py
This forces files in a project to be opened as UTF-8.
On Windows, the default seems to be CP-1252 which led to some error while decoding files in some project.
Since UTF-8 is already the default on Linux and macOS, I think it might make more sense to enforce it on Windows too.
=> Force files to be opened as UTF-8

CHANGELOG.md, brownie/_cli/__main__.py, brownie/_cli/run.py, tests/cli/test_cli_main.py
I've added a `-r` cli flag for the `brownie run` cli command which raises any exceptions to the caller instead of doing a system exit. I've noticed a system exit breaks the auto-capturing of exceptions with sentry because the excepthooks are not triggered at all.
With this addition I could verify that running a brownie script with the current [sentry_sdk](https://github.com/getsentry/sentry-python) works and automatically captures any unhandled exceptions like expected.
I've just modified the `except` blocks slightly to check for the flag and preserve the existing logic if it's not present.
```
$ echo "1/0" > scripts/fail.py
$ brownie run fail -r
Traceback (most recent call last):
File "/usr/local/bin/brownie", line 8, in <module>
sys.exit(main())
File …
```
=> CLI flag for run command to raise exceptions to the caller

CHANGELOG.md, brownie/network/contract.py, docs/config.rst, tests/network/contract/test_contract.py
I've noticed that there's an issue with the chainlink contract `0x514910771AF9Ca656af840dff83E8264EcF986CA` wrt. to overloaded events. This contract is both `ERC-20` and `ERC-677` based and so it emits both types of events which have a different signature and can't be matched properly with log filters. AFAIS, overloaded events have been fixed in solidity compiler version `0.4.17`, the contract defines `0.4.16` in its pragma version. The fact that brownie doesn't compile solidity contracts with version `<0.4.22` causes it to use the given abi from the explorer etherscan which is also incomplete in terms of overloaded events. To overcome this issue and generate a more complete abi I've added a solc compiler setting that enables the download of the latest patch version of a given compiler …
=> feat: adding a use_latest_patch option to solc compiler config

CHANGELOG.md, brownie/network/contract.py, docs/api-network.rst
- fix: inconsistency between `__call__` and `call` arguments in `OverloadedMethod`
- feat: add state override support to contract calls
- docs: add docs about eth_call override
Added basic support for [state override](https://geth.ethereum.org/docs/rpc/ns-eth) feature of `eth_call`. It allows ephemerally changing the state of any addresses before call, including balance, nonce, code, storage slots.
Added an optional `override` argument to `ContractCall` and to everything that plugs into it.
See example provided in the docs.
=> feat: eth_call state override for contract methods

CHANGELOG.md, brownie/exceptions.py, brownie/network/account.py
Exception handling seems to be failing in a few cases with Ganache 7, which is now the latest stable version.
This seems a bit hacky overall but does seem to do the job for our fairly large test suite, so hopefully, it should be better than nothing. It should also not introduce any regression since most of the additions only occur if the logic already in place failed to handle the exception.
1. With the latest ganache, for some reason, web3py does not raise a `ValueError` when a contracts revert so we manually create a `VirtualMachineError` in Brownie when the receipt status is `0` otherwise, we have an attribute error in Brownie because the exception is `None`. This works for almost everything but we lose the PC and a few other nice-to-have features. I think that the longer-term fix …
=> Fix exception handling

brownie/data/network-config.yaml
- Changed rpc url of fantom mainnet to the new rpc gateway recommended by fantom
- edited network-config.yml
- Try running brownie in ftm-main-fork network and it should work now,while previously it didnt
=> fix: update fantom rpc to new rpc

CHANGELOG.md, brownie/network/rpc/ganache.py
Ganache changed their CLI flags in version 7, which breaks Brownie, especially because `--chainId` is not a thing anymore, it's now `--chain.chainId`.
We now check the current version of ganache and use the appropriate flags.
Installing Ganache 7 and running a console in non-development network should do it
```
brownie console --network mainnet-fork
```
=> Support ganache 7 cli flags

CHANGELOG.md, brownie/project/main.py
Fix issue with the current incremental compilation causing all the contracts to recompile every time.
Improved the compiler comparison to avoid comparing things such as "v0.8.10" and "v0.8.10+commit.fc410830" or so.
Compiling any project where the Solidity compiler version is specified should be enough to reproduce.
=> Fix incremental compilation

brownie/project/main.py, tests/project/main/test_main_project.py
Related issue: #1368 
Introduces the `raise_if_loaded` boolean argument, which is `True` by default. Default behaviour is the previous behaviour of `brownie`, but if `raise_if_loaded=False` them the loaders do not raise a `ProjectAlreadyLoaded` error when a caller tries to load a previously loaded project.
`project.load` quietly returns the previously loaded `Project` instance, and `project.main.Project.load` short-circuits (returning `None`).
```bash
pytest tests/project/main/test_main_project.py::test_load_does_not_raise_when_raise_if_loaded_is_false
```
=> Improved project load

CHANGELOG.md, brownie/_cli/networks.py, brownie/_config.py, brownie/data/network-config.yaml, brownie/data/providers-config.yaml, docs/network-management.rst, requirements-dev.txt, tests/cli/test_cli_networks.py
Added support for Alchemy built-in
https://github.com/eth-brownie/brownie/issues/1177
I added a `providers-config.yaml` to the `.brownie` dir. Now, if you want to switch from Infura to Alchemy, you set your `WEB3_ALCHEMY_PROJECT_ID` and run:
```
brownie networks set_provider alchemy
```
Try it out!
1. Add a `provider` flag to your infura network of choice.
```
brownie networks modify mainnet provider=infura
```
Then, swap it to alchemy
```
brownie networks set_provider alchemy
```
For some reason, a few tests locally keep failing for me... wondering if I can get some help cleaning up the last few.
=> added alchemy and provider support

CHANGELOG.md, brownie/project/compiler/__init__.py, brownie/project/main.py, docs/compile.rst, tests/project/compiler/test_main_compiler.py
Allow to override the `evm_version` per language, e.g.
```yaml
compiler:
evm_version: london
solc:
version: 0.8.9
vyper:
evm_version: istanbul
```
`compile_and_format` can now either take a `string` or a dict that must map all the used languages (`Vyper` and `Solidity`) to their desired EVM version.
The change is fully backward-compatible.
Try the YAML config given above.
=> Allow to override the EVM version per language when compiling

CHANGELOG.md, brownie/_cli/networks.py, brownie/network/rpc/ganache.py, docs/network-management.rst
Allow configuring Ganache's `allowUnlimitedContractSize`
Add the flag to `ganache.py` and the CLI
```
brownie networks modify development unlimited_contract_size=true
```
=> Allow to use unlimited contract size with ganache-cli

brownie/network/contract.py
Fix a bug in `OverloadedMethod.__call__` where passing `block_identifier` and `override` would raise when `fn` is a `ContractTx`.
Related to #1412
=> fix: only pass kwargs if not None

docs/compile.rst
Otherwise the import doesn't work. I guess alternatively the python export can be changed.
Fixed a typo in the docs.
```py
>>> from brownie.project.compiler import install_vyper
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ImportError: cannot import name 'install_vyper' from 'brownie.project.compiler' (/usr/lib/python3.9/site-packages/brownie/project/compiler/__init__.py)
>>> from brownie.project.compiler.vyper import install_vyper
>>>
```
=> Fixing Docs Typo

CHANGELOG.md, brownie/network/contract.py, brownie/network/state.py, tests/network/contract/test_contract.py, tests/network/contract/test_interface.py
I've disabled the persistence of interfaces into the deployments db.
Related issue: #1092
- Added a new function param `persist: bool = True` to several contract methods
- Passing `persist=False` for interfaces
- Added helper function `Contract.remove_deployment()`
I've created some new tests in:
- test_contract.py
- test_interfaces.py
=> Make contract deployments optional, disabled for interfaces

brownie/network/contract.py
Correctly pass the `allow_revert` kwarg when deploying a contract.
=> fix: pass allow_revert on deployment

brownie/network/rpc/ganache.py, tests/network/state/test_blocks.py
Fix an issue with `chain.mine` where setting a new timestamp wasn't remembered in subsequent blocks.
This seems to be changed behavior from ganache 6 to 7 but I can't find any documentation on it, so not sure if it's intentional.
When calling `evm_mine` with a timestamp, also call `evm_setTime`.
=> Ensure chain time is correct when using `chain.mine` with ganache 7

brownie/convert/datatypes.py, tests/convert/test_return_value.py, tests/data/brownie-test-project/contracts/BrownieTester.sol
When you compare a ReturnValue that has a string containing a single space, it fails to convert the string to Wei, which isn't rescued and then treated as a string like I believe was intended.
`TypeError: Cannot convert str 'bar baz' to wei.`
=> Fix ReturnValue comparison of tuples containing strings

brownie/_gui/source.py
Selecting any text just causes the selection to disappear, instead of highlighting relevant opcodes. This PR fixes this.
Related PR: #1512
After releasing a button, `SourceNoteBook._search()` is triggered to find opcodes related to given source code. When searching for opcodes, it filters the `pcMap` with a term `frame._label in v["path"]`. `v["path"]` here is an integer index, while `frame._label` is a string path to the source file. As this compares apples-to-oranges, it always evaluates to false and triggers the code branch that clears selection.
In this PR I've changed the term to compare label to label.
I believe GUI has no tests, so you need to run it manually and select some source code.
- [N] I have confirmed that my PR passes all linting checks - No, I'm getting mypy issues …
=> fix: gui - highlight opcodes when selecting source

Dockerfile
I updated Dockerfile for a fix to following warning message during its installation:
```npm WARN deprecated ganache-cli@6.12.2: ganache-cli is now ganache; visit https://trfl.io/g7 for details```
Fix: npm WARN deprecated ganache-cli@6.12.2: ganache-cli is now ganache; visit https://trfl.io/g7 for details
Updated npm before installing ganache:
```
RUN npm install n -g \
&& npm install -g npm@latest
RUN npm install -g ganache
```
=> Fix: npm WARN deprecated ganache-cli@6.12.2: ganache-cli is now ganache

brownie/_cli/networks.py
Currently, a network RPC address like `https://stardust.metis.io/?owner=588` fails with
```
Brownie v1.17.1 - Python development framework for Ethereum
('host=https://stardust.metis.io/\\?owner\\=588', 'chainid=588')
File "brownie/_cli/__main__.py", line 64, in main
importlib.import_module(f"brownie._cli.{cmd}").main()
File "brownie/_cli/networks.py", line 68, in main
fn(*args["<arguments>"])
File "brownie/_cli/networks.py", line 111, in _add
args = _parse_args(args)
File "brownie/_cli/networks.py", line 278, in _parse_args
raise ValueError("Arguments must be given as key=value") from None
```
This fixed this.
=> Handle equal signs in network rpc address

brownie/project/main.py
Fix typo, changing "Package is aleady installed" to "Package is already installed" when installing an already-installed package.
Changed FileExistsError() message in project/main.py line 809 to solve a typo.
=> fix: typo "Package is al(r)eady installed"

brownie/_gui/opcodes.py
I fixed the following exception that happens when clicking opcode in right pane:
```
Exception in Tkinter callback
Traceback (most recent call last):
File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
return self.func(*args)
File "/home/kaz/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/brownie/_gui/opcodes.py", line 121, in _select_bind
note.set_active(pcMap["path"])
File "/home/kaz/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/brownie/_gui/source.py", line 84, in set_active
self.select(self.get_frame(label))
File "/home/kaz/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/brownie/_gui/source.py", line 50, in get_frame
return next(i for i in self._frames if i._label == label)
StopIteration
```
Opcode on-click callback (`_select_bind` in …
=> fix: gui - highlight source code when selecting opcode

brownie/_config.py, brownie/project/scripts.py
Fixed 3 bugs:
1. failed to load python scripts on windows when running "brownie run xxx.py".
```
File "C:\Users\guli\Anaconda3\envs\ethereum\lib\site-packages\brownie\_cli\run.py", line 50, in main
return_value, frame = run(
File "C:\Users\guli\Anaconda3\envs\ethereum\lib\site-packages\brownie\project\scripts.py", line 53, in run
module = _import_from_path(script)
File "C:\Users\guli\Anaconda3\envs\ethereum\lib\site-packages\brownie\project\scripts.py", line 149, in _import_from_path
_import_cache[import_str] = importlib.import_module(import_str)
File "C:\Users\guli\Anaconda3\envs\ethereum\lib\importlib\__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
```
2. if OS default encoding is different from the script's file encoding, "brownie …
=> fixed 2 critical bugs on windows 

CHANGELOG.md, brownie/project/main.py
=> Ensure .env file exists for installed packages

CHANGELOG.md, brownie/data/network-config.yaml, brownie/network/rpc/__init__.py, brownie/network/rpc/anvil.py, docs/install.rst
Related issue: #1526
Copied the hardhat rpc file and modified it a tiny bit to work with anvil.
```
$ brownie console --network anvil-fork
>>> chain.time()
1653513634
>>> chain.mine()
14844123
>>> chain.time()
1653513638
>>> chain.sleep(111111111)
>>> chain.mine()
14844124
>>> chain.time()
1764624758
>>> chain.mine(3)
14844127
```
=> initial anvil support

brownie/project/compiler/vyper.py
Catch the `StopIteration` that happens sometimes when compiling vyper 0.3.3.  This is a stopgap solution but it fixes the issue today until we can find a better fix tomorrow.
=> fix: handle StopIteration when building vyper pcMap

docs/network-management.rst
Fixed typo in command to list providers.
`$ brownie networks providers_list` -> `$ brownie networks list_providers`
=> Fix typo in network management doc

CHANGELOG.md, brownie/project/compiler/vyper.py
Vyper 0.3.4 adds a signature to the bytecode. This causes an error when compiling in Brownie because the source map is empty before the opcodes queue is exhausted in `_generate_coverage_data()` in `brownie/project/compiler/vyper.py`.
Related issue: #1566 and https://github.com/vyperlang/vyper/issues/2955
Check for the signature when the source map is empty, and exit the `while` loop.
=> feat: add vyper version bytecode check

CHANGELOG.md, brownie/network/transaction.py
Related issue: #1549 
Set receiver in TransactionReceipt ```None``` when transaction dict has no ```to``` attribute.
Existing unit tests
=> Fix: "to" field is null during contract creation

CHANGELOG.md, brownie/network/rpc/anvil.py
Add the following CLI flags for Anvil: `chain_id`, `default_balance`, `gas_limit`
Related issue: #1526 
Add a few flags to `CLI_FLAGS` variable in `anvil.py`
The following settings (backward compatible with ganache): 
`cmd_settings: {'chain_id': 1, 'default_balance': 10000000000, 'fork': mainnet, 'gas_limit': 12000000, 'port': 8545}`
It now launches anvil with the correct settings
```
$ brownie console --network anvil-test
Launching 'anvil --chain-id 1 --initial-balance 120000000000000 --fork-url <mainnet_rpc> --gas-limit 12000000 --port 8545
>>> a[0].balance()
120000000000000000000000000000000
>>> chain.id
1
>>> chain.time()
1654069248 
```
=> Add anvil cli flags

brownie/project/main.py
Split package_id with only the first '@'. This prevents raising ValueError when '@' is in the name of the version. For example, adding 'superfluid-finance/protocol-monorepo@ethereum_contracts@v1.3.0' to dependencies in brownie-config.yaml raises an ValueError. ethereum_contracts@v1.3.0 is the name of the version.
Change `package_id.split("@")` -> `package_id.split("@", 1)`.
=> fix parsing of dependencies with @ in version

CHANGELOG.md, brownie/project/compiler/vyper.py
Terminate coverage generation early for vyper versions >= 0.3.4
Related issue: #1578 
Check the version set globally and terminate early if >= 0.3.4
=> fix: vyper coverage data generation for version >= 0.3.4

CHANGELOG.md, brownie/project/main.py
This solves an issue where some fixtures that were dependencies
of the project would be found right after compilation but not
in subsequent runs of the tests.
Only remove build files if they do not have any dependents in the project.
Add an out-of-project dependency and compile twice
=> Avoid removing dependencies from the build

brownie/network/contract.py
Currently, brownie did not handle remappings when trying to get source in `from_explorer`. 
Fetched remappings and utilized @0xCalibur time.
Try to get source code for a contract with from_explorer that uses remappings, e.g. those compiled with forge.
=> Added Support for Remappings in from_explorer

CHANGELOG.md, brownie/data/network-config.yaml
Update Moonscan API for Moonbase Alpha. Previously, the Moonscan API for the Moonbeam Production mainnet was specified instead of the one for Moonbase Alpha (Testnet). 
=> Correct Moonscan API for Moonbase Alpha

brownie/network/contract.py
fix coverage when vyper immutables
patch the bytecode, pretend like we actually know what is in the data section
`brownie test --coverage` on a file with immutables
=> handle vyper immutables

requirements-windows.txt, requirements.txt
I encountered issues with Python 3.11 compatibility in a project using `eth-brownie`. I fixed the problem of dependencies and tested with a matrix strategy for python 3.8, 3.10 and 3.11 on ubuntu, mac and windows. The solution helped a lot and I thought to share it with brownie core :)
I've also seen this reported here: [#](https://github.com/eth-brownie/brownie/issues/1640) and it should fix that too.
Upgraded yarl and added version constraints for bitarray for compatibility with Python 3.11.
A pip install and running the tests should do it.
Not sure how the checklist applies but I'll see if any CI is triggered automatically and fill in the list if necessary.
=> Python 3.11 compatibility - upgrade yarl and set versions for bitarray

brownie/project/compiler/__init__.py, brownie/project/compiler/solidity.py, brownie/project/compiler/vyper.py, tests/project/compiler/test_vyper.py
=> update vyper default evm version to paris

brownie/network/contract.py
Renamed a variable from `l` to `x`. This was causing flake8 to fail and consequently `tox`.
From [PEP8](https://peps.python.org/pep-0008/#names-to-avoid):
> [Prescriptive: Naming Conventions](https://peps.python.org/pep-0008/#prescriptive-naming-conventions)
[Names to Avoid](https://peps.python.org/pep-0008/#names-to-avoid)
Never use the characters ‘l’ (lowercase letter el), ‘O’ (uppercase letter oh), or ‘I’ (uppercase letter eye) as single character variable names.
In some fonts, these characters are indistinguishable from the numerals one and zero. When tempted to use ‘l’, use ‘L’ instead.
=> chore: fix E741 rule in flake8

brownie/network/state.py
Closes https://github.com/eth-brownie/brownie/issues/1144
A simple check that the Key exists to avoid KeyError
Related issue: #1144
Local and GitHub Action tests used to fail with KeyError in https://github.com/oceanprotocol/df-py/
Investigated against the existing issue in the brownie repo (#1144). Using `from_abi` did not fix it when used as a combination (both `at` and `from_abi`). Currently in df-py we are rewriting the problematic line from brownie/network/state.py using a `sed` command:
https://github.com/oceanprotocol/df-py/blob/ee7a5f9b1449ed3d308639add306d0c0f98a4a7e/.github/workflows/test.yml#L57
However, it seems like a no-hassle fix and would help a lot of devs using brownie.
=> Ensure contract address exists in contract map before deleting

CHANGELOG.md, brownie/project/main.py
On Windows without utf-8 encoding by default, there can be errors like `UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 52: illegal multibyte sequence` when contracts are being read.
Related issue: None
Using encoding='utf-8' for contracts
I cloned https://github.com/RockX-SG/stake and made brownie work with the contracts on Windows 10.
=> encoding='utf-8' for reading contracts

docs/tests-coverage.rst
Changed misspelled word: parralel -> parallel
=> Typo in docs

brownie/network/transaction.py
The transaction trace didn't include the encoded return value of function calls if there was no source code contact information. This PR always includes the return data (when not null). If contract source code information is available, the `returndata` gets overridden by `return_value.` 
Related issue: https://github.com/eth-brownie/brownie/issues/1360
I've decoded the `returndata` in the loop that loops through the trace steps before it chooses to ignore a step that doesn't have contract source code information available.
Run `call_trace(True)` on any transaction. Example before: 
Example after (including this change):
=> Include encoded return data in transaction trace

CHANGELOG.md, brownie/data/network-config.yaml, docs/network-management.rst
Add polygon networks to default network-config.yaml
Hedera's JSON-RPC relay based on https://swirldslabs.com/hashio/ and https://github.com/hashgraph/hedera-json-rpc-relay. Swirlds Labs part of Swirlds (https://swirldslabs.com/hashio/), a Hedera council member, is providing an implementation of JSON-RPC relay for Hedera based on https://github.com/hashgraph/hedera-json-rpc-relay
That is the contract:
https://hashscan.io/testnet/transaction/1672895810.943115003?tid=0.0.902-1672895801-932790323
=> Add Hedera's JSON-RPC relay to default network-config.yaml

brownie/test/managers/master.py
Closes #1648
Corrected PyTest Isolation Guide URL
Related issue: #1648
Corrected the URL to the correct one.
Run the test suite.
=> Correct URL to PyTest Isolation Guide

brownie/network/contract.py
added an option to suppress the console output when executing a transaction
Related issue: #1634
added a parameter ```silent: bool = False``` on ```transact```,  so now optional argument ```silent = True``` can be passed to suppress the console output
```contract.someTransactMethod('argument', {'from':accounts[0]}, silent=True)```
=> execute transactions silently

brownie/network/account.py
Add a kwarg `allow_retry` to `account.load` to allow re-attempt of password.
=> Allow retry password on `account.load`

brownie/data/default-config.yaml, brownie/network/account.py
* default to using EIP1559 gas pricing of transactions when connected to a live network
* fall back to legacy style if the network does not support
=> Default to EIP1559-style transactions on live networks

brownie/exceptions.py, brownie/network/account.py, brownie/network/contract.py, brownie/network/middlewares/ganache7.py, brownie/network/middlewares/hardhat.py, brownie/network/transaction.py, brownie/project/compiler/solidity.py
Add support for typed errors as implemented in solc `0.8.x`
Tested it locally and seems to be working properly on the lastest versions of hardhat and ganache.
Closes #1108
=> Support for custom / typed errors

.readthedocs.yaml
Add `.readthedocs.yaml` - hopefully this gets the docs to compile properly again.
=> ReadTheDocs configuration file

brownie/network/middlewares/caching.py, brownie/network/web3.py
Missed a few spots of converting camelCase to snake_case when upgrading web3 to v6.
I realize that brownie subclasses `Web3` and so the breaking changes here probably denoted a v2 bump...  lets just not talk about that.
=> camelCase -> snake_case fixes

brownie/network/middlewares/caching.py
Restart the block filter loop automatically if it crashes. This sometimes happens from a temporary loss of internet connection.  previously you'd have to either restart brownie altogether, or `web3.reset_middlewares()`
I've been running brownie locally with these edits for a week or so now and it seems to work.  Tried suspending my laptop a few times, as well as restarting my router to mess up the connection.
=> Improvements to caching middleware

brownie/network/multicall.py
Fix a bug in `multicall` where it stops working if a call reverts.
`try/finally` to ensure the `__code__` is changed back even if an exception is raised
=> `multicall` - reset call code even if call reverts

brownie/project/sources.py
Added supporting the new pragma string for Vyper 0.3.10 according to [the docs](https://docs.vyperlang.org/en/latest/structure-of-a-contract.html#version-pragma)
Closes #1745
Changed RegExp pattern to obtain the version of compiler
=> fix versions parsing RegExp

brownie/exceptions.py
=> fix: `TypeError` when outputting custom errors

brownie/project/main.py
Allow installing a package where there is no `contracts` folder, and multiple folders contain smart contracts.
This helps when dealing with mono-repos, or projects using foundry where unit tests are also marked as `.sol`.
=> loosen package install restrictions

brownie/data/default-config.yaml, brownie/network/middlewares/caching.py, docs/config.rst
Related issue: # N/A
I added a `eager_caching` setting to brownie-config.yaml which tells brownie not to enable the background caching thread
easy!
pending
=> feat: add `eager_caching: true` to default-config.yaml

brownie/exceptions.py
Related issue: #1757
Please refer to diff.
=> Fix error_code decoding

brownie/convert/datatypes.py
Fix an bug that prevented nested tuples from correctly having their dict keys available.
Also, now keys with no name are given a generic name so that they are still available.  Technically this is a breaking change but meeeeh, it was also broken before so working correctly now is a net win I think :)
=> fix: correct dict keys for nested tuples

brownie/network/middlewares/geth_poa.py
For live networks, determine if the POA middleware is required by looking at the latest block.  For dev networks, check the first block.
Closes #1762
=> fix: target different blocks for live/dev network

brownie/network/contract.py
If compilation fails during `Contract.from_explorer`, fall back to the ABI.
=> Fall back to ABI when `Contract.from_explorer` compilation fails

brownie/network/transaction.py
in recent versions of anvil sometimes brownie ends up in a race condition when waiting for a tx confirmation. the bug results in`KeyError: 'blockNumber'`.
the root cause is anvil retuning no `blockNumber` field in `eth_getTransactionByHash` for pending transactions.
the bug was introduced here https://github.com/alloy-rs/alloy/pull/523
use `tx.get('blockNumber')` instead of `tx['blockNumber']`
run a bunch of transactions, it doesn't happen every time. it's easier if you run anvil alongside, so you can see its output. the bug manifests when there is a `eth_getTransactionByHash` before `Transaction` printout.
```
eth_sendTransaction
eth_getTransactionByHash
eth_getCode
Transaction: 0xc94c6c69570ca19763eda0a33a9b6a67803a5fa1fca2861ed2f4c08607edf0fb
Gas used: 21000
```
=> fix: crash when waiting for a tx confirmation

brownie/project/flattener.py
During source file verification, recursively check each parent folder to find the absolute path of a file import.
Related issue: #1775 
Recursively check each `.parent` of `source_file_dir` until the path exists. If the check fails, raise a `FileNotFoundError`.
I'm unsure how to go about writing tests for this, but confirm the behavior works for my case.
=> Search parent paths for import file during source verification

brownie/network/contract.py, brownie/project/flattener.py
=> chore: fix typos

brownie/network/transaction.py
Fix a long-standing bug (at least 3 years now) where transactions could sometimes fail with "tx dropped without known replacement" at the moment they confirm.
The shorter the blocktimes, the more likely you were to hit the bug. I'd always blamed it on poor load-balancing for L2/sidechain RPC infra but it turns out it was my fault :rofl:
=> Await tx confirmation by watching nonce

brownie/project/compiler/solidity.py, brownie/project/compiler/vyper.py
Removed the `tdqm` progress bar when installing the compiler.  Turns out this makes the install process magnitudes slower :scream:   Go figure.
=> Remove tdqm progress bars

brownie/network/contract.py, brownie/network/state.py
* when instantiating a `Contract` object, the cached bytecode is used if available to avoid a call to `eth_getCode`
* `Contract.from_abi` no longer overwrites full contract artifacts
The first item improves load times fairly significantly for me.
=> Caching fixes

.github/workflows/core-ganache-3.10.yaml, .github/workflows/core-ganache-3.11.yaml, .github/workflows/core-ganache-3.12.yaml, .github/workflows/evm.yaml, .github/workflows/functionality.yaml, .github/workflows/lint.yaml
This PR limits each github workflow to 1 concurrent run per branch to avoid annoying emails and the queue backing up.
Does not impact the library in any way.
Added a short snippet to each workflow's yaml file
Just merge and see
=> Limit workflow concurrency

CHANGELOG.md, docs/install.rst
Replaced occurrences of `https://github.com/foundry-rs/foundry/tree/master/anvil` with `https://github.com/foundry-rs/foundry/tree/master/crates/anvil`.
=> fix: Broken links

CHANGELOG.md, brownie/convert/datatypes.py, requirements.in, requirements.txt
I saw a low-hanging-fruit optimization opportunity in eth_utils.to_checksum_address
I re-implemented eth_utils.to_checksum_address in c [here](https://github.com/BobTheBuidler/cchecksum), published a lib to pypi, dropped the drop-in replacement into brownie
=> feat: implement cchecksum for ~2x faster checksumming

brownie/network/middlewares/geth_poa.py
On Polygon networks, anvil in forked development mode doesn't throw `ExtraDataLengthError` on the first block. So, I changed the GethPOAMiddleware to try both the first block and latest block. This is similar to apeworx implementation here:
https://github.com/ApeWorX/ape-hardhat/pull/133
Related issue: #1762
ran anvil locally
```
anvil --accounts 10 --fork-url <REDACTED> --gas-limit 12000000 --port 8545 --chain-id 137 &
```
connect web to anvil
```
web3.connect('http://localhost:8545')
```
verify we hit the exception on latest block, but not on first block
```
>>> try:
...     web3.eth.get_block("latest")
... except Exception as e:
...     print(type(e))
... 
eth_getBlockByNumber
<class 'web3.exceptions.ExtraDataLengthError'>
```
```
>>> try:
...     web3.eth.get_block(0)
... except …
```
=> [fix] GethPOAMiddleware on Polygon networks with anvil fork

brownie/network/event.py
This PR will eliminate 1 list comprehension and x-2 global name lookups, where x is the number of logs in the iterable, per _decode_logs call
Might seem silly but profiling showed we spent an inordinate amount of time on these lines.
=> chore: refactor events with `map`

brownie/utils/docopt.py
I thought 2 numbers were being added, so I summed
I was wrong, they were strings
sum is type error
now I join
you join too
=> fix: type error

requirements.txt, tests/conftest.py, tests/network/contract/test_contract.py, tests/network/test_web3.py, tests/network/transaction/test_revert_msg.py, tests/network/transaction/test_trace.py
We could consider fixing them later on with alt-l1 or l2 networks
Disabled 2 tests that used goerli, and 1 that used rinkeby
=> fix(test): disable tests on goerli and rinkeby

CHANGELOG.md
It was 2x at release but its 8x now :) 
I also added something to the release notes for #1791
=> chore: update changelog with most recent benchmark result

.github/workflows/pip-compile.yaml
Hey ! GitHub‑hosted runners now use Node 20, so checkout v4 is required
This PR updates all workflows to actions/checkout@v4 , no functional changes expected
=> ci: bump actions/checkout to v4

tox.ini
One of the test failures in the runner shows:
```
def test_getitem_negative_index(devnetwork, accounts, chain, web3):
block = chain[-1]
>       assert block == web3.eth.get_block("latest")
E       AssertionError: assert AttributeDict...'uncles': []}) == AttributeDict...drawals': []})
E         Use -v to get the full diff
```
so I decided to modify the test runner so the tests fail verbosely
added the -v flag to each test command in tox.ini
the tests will run on this PR
=> feat(test): run tests verbosely

requirements.txt, tests/conftest.py
Maybe a better solution here would be a threading.Lock?
=> fix(test): add handler for race condition in `network` fixture setup

requirements.txt, tests/conftest.py
The threading.Lock we added did not fully solve our issue, so I readded the try: except ConnectionError: block that we removed when we added the lock
=> fix(test): network.disconnect race condition

tests/network/contract/test_persistence.py
This fixes that race condition we've been chasing, in one place anyway
=> fix(test): add ConnectionError handler in _reconnect helper

tests/conftest.py
=> fix(test): race condition in testing runners when calling project.load

brownie/network/__init__.py, requirements-dev.txt, requirements.txt
this PR should make the types visible downstream ie in downstream repos importing them from the main `__init__.py`
=> feat(mypy): network constant types

CHANGELOG.md, brownie/_singleton.py
counterintuitively, when you supply type hints for a metaclass' call method, it breaks typing for the created instances which all resolve to the `__call__` method's return type (currently `Any`)
This PR allows all singleton-based classes to type correctly.
clone it and mouseover the instances in your IDE
=> fix(mypy): _Singleton metaclass typing

brownie/convert/datatypes.py
The docstring for the `Wei` class contained a hex string example with
a stray backslash at the end.
This commit removes the unnecessary character to correct the example
and prevent confusion for developers.
=> docs(convert): Fix typo in Wei docstring example

.github/workflows/compile.yaml
=> fix(cicd): let gh runner force push to compile branch

brownie/network/contract.py, brownie/network/transaction.py, brownie/network/web3.py
Corrected misspellings:
- `compatability` → `compatibility`
- `seperate` → `separate`
=> Fix typos across multiple files
